=== fink/website/xml/news/finknews.dtd
<!ENTITY % block "codeblock | ol | p | ul" >
<!ENTITY % inline "#PCDATA | code | em | extlink | filename | link | tt" >


<!-- Root element -->
<!ELEMENT news ( cvsid, newsitem+ ) >
<!ELEMENT cvsid ( #PCDATA ) >

<!-- Structure -->
<!ELEMENT newsitem ( date, headline?, body ) >

<!ELEMENT date ( #PCDATA ) >
<!ELEMENT headline ( #PCDATA ) >
<!ELEMENT body ( %block; )* >


<!-- Block elements -->
<!ELEMENT codeblock ( #PCDATA | em )* >
<!ELEMENT p ( %inline; )* >

<!-- Links -->
<!ELEMENT link ( #PCDATA ) >
<!ATTLIST link url CDATA #REQUIRED >

<!ELEMENT extlink ( #PCDATA ) >
<!ATTLIST extlink url CDATA #REQUIRED >


<!-- Inline -->
<!ELEMENT code ( #PCDATA | em )* >
<!ELEMENT em ( #PCDATA ) >
<!ELEMENT filename ( #PCDATA ) >
<!ELEMENT tt ( #PCDATA ) >


<!-- Lists -->
<!ELEMENT ol ( li+ ) >
<!ELEMENT ul ( li+ ) >

<!ELEMENT li ( %inline; | codeblock | p )* >

=== fink/website/xml/news/news.ja.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE news SYSTEM "finknews.dtd">
<news lang="ja">
 <cvsid>$Id: news.ja.xml,v 1.95 2021/11/03 5:08:00 nieder Exp $</cvsid>
<newsitem>
 <date>2021-11-03</date>
 <headline>fink-0.45.4 released</headline>
 <body>
  <p>The Fink Project has released fink-0.45.4. This is a minor upgrade to support XQuartz 2.8.</p>
  <p>This release does not yet support macOS 11 (Big Sur) or macOS 12 (Monterey). Support for those two releases is coming soon.</p>
 </body>
</newsitem>
<newsitem>
 <date>2021-03-06</date>
 <headline>fink-0.45.3 released</headline>
 <body>
  <p>The Fink Project has released fink-0.45.3. This is a minor behavioral fix for an issue introduced in 0.45.2. With this release, the default prefix for new installs is reverted to <code>/sw</code> for all macOS versions from 10.14 and earlier. Newer releases still default to <code>/opt/sw</code>. This will allow installs on macOS 10.14 and earlier to continue to use any available binary distributions. There are no other functional changes in this release compared to fink-0.45.2.</p>
  <p>This release does not yet support macOS 11 (Big Sur).</p>
 </body>
</newsitem>
<newsitem>
 <date>2020-10-02</date>
 <headline>fink-0.45.2 released</headline>
 <body>
  <p>The Fink Project has released fink-0.45.2. This release provides support for all macOS releases up to and including 10.15.7. Most importantly, it changes the default install path location to <code>/opt/sw</code> for all supported macOS releases. This release also fixes bootstrapping problems when installing on macOS 10.15 with Xcode12. Run <code>fink selfupdate</code> to install the latest version. This release does not need any special preparation apart from those listed below if upgrading to macOS 10.15 from an earlier macOS release.</p>
  <p>This release does not yet support macOS 11 (Big Sur).</p>
 </body>
</newsitem>
<newsitem>
 <date>2020-03-28</date>
 <headline>fink-0.45.1 released</headline>
 <body>
  <p>The Fink Project has released fink-0.45.1. This release provides support for all macOS releases up to and including 10.15.4, as well as support for users running the zsh shell. Run <code>fink selfupdate</code> to install the latest version. This release does not need any special preparation apart from those listed below if upgrading to macOS 10.15 from an earlier macOS release.</p>
 </body>
</newsitem>
<newsitem>
 <date>2019-10-27</date>
 <headline>Further 10.15 (Catalina) and Xcode11 upgrade details</headline>
 <body>
  <p>If upgrading to macOS 10.15 (Catalina) from an earlier macOS release, your existing Fink install will cease to work if installed outside <code>/opt</code> (such as to the previous default <code>/sw</code>) and must be reinstalled from scratch using Fink release 0.45.0 or later.</p>
  <p>The old Fink install is archived into <code>/Users/Shared/Relocated Items</code>. It's possible to manually recover downloaded source archives and configuration files from there to use in a new Fink install. However, it's not possible to reuse built .deb packages because they hardcode the original path that contained Fink.</p>
  <p>Upgrade and installation hints if existing Fink install is outside <code>/opt</code>:</p>
  <ul>
    <li>If doing a fresh Fink install on any macOS version, install Fink into <code>/opt/sw</code>.</li>
    <li>If you haven't yet updated to macOS 10.15, run this command to capture the list of your currently installed packages: <code>for i in `/bin/ls -1 /sw/var/lib/dpkg/info/*.list`; do basename -s .list $i >> ~/my_fink_packages.txt; done</code>.</li>
    <li>If you have already updated to macOS 10.15 but had Fink installed somewhere outside <code>/opt</code> before your system upgrade, use the above command (with modified path to the "Relocated Items" location as necessary) to capture the packages you previously had installed on your older macOS release. For example: <code>for i in `/bin/ls -1 "/Users/Shared/Relocated Items/sw/var/lib/dpkg/info/"*.list`; do basename -s .list $i >> ~/my_fink_packages.txt; done</code></li>
    <li>Once you have captured your list of previous packages, upgraded to macOS 10.15, and installed Fink into <code>/opt</code>, run the following command to batch build and reinstall your previous Fink packages: <code>cat ~/my_fink_packages.txt | xargs fink reinstall</code>. Note that some packages do not exist on macOS 10.15, so you might need to hand edit the file <code>my_fink_packages.txt</code> to remove the missing packages before trying to reinstall.</li>
  </ul>
 </body>
</newsitem>
<newsitem>
 <date>2019-10-02</date>
 <headline>10.15 (Catalina) and Xcode11 information</headline>
 <body>
  <p>Fink 0.45.0 and up support the upcoming 10.15 release, but there are some important things to note:</p>
  <ul>
    <li>Apple locked down the <code>/ (root)</code> directory where Fink normally installs (in <code>/sw</code> by default), so existing Fink installs may become read-only upon updating to 10.15.</li>
    <li>Xcode11 introduces some known breakages (with no known fixes at this time) to important packages like gcc, so not everything will build yet.</li>
  </ul>
  <p>Once macOS 10.15 is officially released, we suggest waiting to upgrade until we know how the system will treat existing installs and we can determine the best upgrade path.</p>
  <p>For anyone installing Fink for the first time (on 10.15beta or an earlier macOS version), we now recommend using <code>/opt/sw</code> as the install location, since that's known to work. The next Fink release after macOS 10.15 is out will use <code>/opt/sw</code> as the default install location.</p>
  <p>Xcode11 is known to currently break building the gccX and several other important packages. If possible (especially 10.14 users), hold off on upgrading to Xcode11 unless you need something specific from it. If you do upgrade to Xcode11, make sure that the Command Line Tools are also upgraded to version 11 for your macOS release.</p>
 </body>
</newsitem>
<newsitem>
 <date>2019-08-05</date>
 <headline>fink-0.45.0 released</headline>
 <body>
  <p>The Fink Project has released fink-0.45.0. This release provides support for macOS 10.14.5 and up, including preliminary support for macOS 10.15beta. This release also provides full support for .app bundles in APFS volumes.</p>
  <p>If your system is still on macOS 10.14.4 or earlier:</p>
  <ol>
    <li>In a terminal window, run <code>fink selfupdate</code> and install <code>fink-0.45.0</code>.</li>
    <li>Update to the latest version of Mojave.</li>
    <li>In a terminal window, run <code>fink reinstall fink</code>.</li>
  </ol>
  <p>If you have already updated to macOS 10.14.5:</p>
  <ol>
    <li>In a terminal window, run <code>fink selfupdate</code> and install <code>fink-0.45.0</code>.</li>
  </ol>
 </body>
</newsitem>
<newsitem>
 <date>2019-06-02</date>
 <headline>Fink mirrors are back</headline>
 <body>
  <p>Thanks to the work of Fink members Chris Z and Justin H, the finkmirrors.net domain is operational once again.</p>
  <p>We are looking for new mirror owners to extend our mirroring service. If you can host a Fink mirror, see <link url="http://finkmirrors.net/">the main Fink Mirrors site</link> for instructions and requirements.</p>
  <p>Thank you for your patience.</p>
 </body>
</newsitem>
<newsitem>
 <date>2019-05-30</date>
 <headline>Issues with macOS 10.14.5</headline>
 <body>
  <p>Apple's release of macOS 10.14.5 updated the system perl version from 5.18.2 to 5.18.4. This update broke bootstrapping fresh installs, as well as existing perl modules dependent on perl-5.18.2.</p>
  <p>Fixes for Fink working on macOS 10.14.5 are tracked <link url="https://github.com/fink/fink/pull/190">on GitHub</link>. </p>
  <p>We apologize for the inconvenience.</p>
 </body>
</newsitem>
<newsitem>
 <date>2019-03-14</date>
 <headline>fink-0.44.1 リリース</headline>
 <body>
  <p>Fink プロジェクトは、 <code>fink-0.44.1</code> をリリースしました。
  これは、基本的にバグ修正リリースで、 bootstrap と <code>Install Fink.tool</code> スクリプトを修正しています。
  さらに、バックグラウンドで最適化アップデートも追加されています。
  <code>fink selfupdate</code> を使用してインストールしてください。</p>
  <p>10.9-10.13 から 10.14 へアップデートする最適な方法は、以下の通りです:</p>
  <p>0) 10.9-10.13 を開始。まだ OS のアップデートをしないでください。</p>
  <p>1) ターミナルで、 <code>fink selfupdate</code> を実行し、 <code>fink-0.44.1</code> をインストールします。</p>
  <p>2) Mojave にアップデート。</p>
  <p>3) ターミナルで、 <code>fink reinstall fink</code> を実行します。</p>
 </body>
</newsitem>
<newsitem>
 <date>2019-02-25</date>
 <headline>ミラーが現在ダウン</headline>
 <body>
  <p>Fink の finkmirrors.net ドメインは現在ダウンしています。
  これは、rsync で selfupdate しているユーザーとバイナリ配布を利用しているユーザーに影響しています。</p>
  <p>Fink ディストリビューションを最新にするには、以下のコマンドを実行してください:</p>
  <ul>
    <li>rsync から git に更新方法を変えるため、 <code>fink selfupdate-git</code> を実行し、</li>
    <li>コンパイル済みパッケージのダウンロードを停止するため <code>fink configure</code> を実行します。</li>
  </ul>
  <p>ご迷惑をおかけして申し訳ございません。</p>
 </body>
</newsitem>
<newsitem>
 <date>2019-01-16</date>
 <headline>fink-0.44.0 リリース</headline>
 <body>
  <p>Fink プロジェクトは、 <code>fink-0.44.0</code> をリリースしました。
  このリリースは、 macOS 10.14 (Mojave) 及び Java 10 をサポートします。
  <code>fink selfupdate</code> を使用してインストールしてください。</p>
  <p>10.9-10.13 から 10.14 へ更新する最適な方法は、以下の通りです:</p>
  <p>0) 10.9-10.13. を実行します。まだ OS はアップデートしないでください。</p>
  <p>1) ターミナルで、 <code>fink selfupdate</code> を実行し、 <code>fink-0.44.0</code> をインストールします。</p>
  <p>2) Mojave にアップデート。</p>
  <p>3) ターミナルで、 <code>fink reinstall fink</code> を実行します。</p>
 </body>
</newsitem>
<newsitem>
 <date>2017-04-18</date>
 <headline>fink-0.43.1 released</headline>
 <body>
  <p>The Fink Project has released <code>fink-0.43.1</code>.  This is a bugfix release.  Use<code>fink selfupdate</code> to install it.</p>
  <p>If you happen to have updated your OS X before updating fink, follow the "Fixing updates when you have installed High Sierra before updating fink" instructions below, and then run <code>fink selfupdate</code> again.</p>
 </body>
</newsitem>
<newsitem>
 <date>2017-03-28</date>
 <headline>fink-0.43.0 released</headline>
 <body>
