=== fink/website/xml/finkdoc.dtd
<!ENTITY % block "codeblock | ol | p | ul" >
<!ENTITY % inline "#PCDATA | code | strong | em | filename | link | varlink | tt | quote | xref" >

<!ENTITY fink_version "0.9.0" >
<!ENTITY fink_tool_version "0.45.4">


<!-- Root elements -->
<!ELEMENT article ( title, shorttitle, cvsid, preface?, section+ ) >
<!ATTLIST article filename ID #REQUIRED >
<!ATTLIST article lang CDATA "en" >
<!ATTLIST article fsroot CDATA "../" >

<!ELEMENT document ( title, shorttitle, cvsid, preface?, chapter+ ) >
<!ATTLIST document filename ID #REQUIRED >
<!ATTLIST document lang CDATA "en" >
<!ATTLIST document section CDATA "documentation" >
<!ATTLIST document fsroot CDATA "../../" >


<!-- Structure -->
<!ELEMENT chapter ( title, shorttitle, preface?, section+ ) >
<!ATTLIST chapter filename ID #REQUIRED >

<!ELEMENT title ( #PCDATA ) >
<!ELEMENT shorttitle ( #PCDATA ) >
<!ELEMENT cvsid ( #PCDATA ) >
<!ELEMENT preface ( p+ ) >

<!ELEMENT section (title?, ( %block; | itemtable )*) >
<!ATTLIST section name NMTOKEN #IMPLIED >
<!ATTLIST section translated (yes|no) "yes" >


<!-- Block elements -->
<!ELEMENT codeblock ( #PCDATA | em | strong )* >
<!ELEMENT p ( %inline; )* >
<!ATTLIST p translated (yes|no) "yes" >


<!-- Inline -->
<!ELEMENT code ( #PCDATA | em | strong )* >
<!ELEMENT em ( #PCDATA ) >
<!ELEMENT strong ( #PCDATA ) >
<!ELEMENT filename ( #PCDATA ) >
<!ELEMENT tt ( #PCDATA ) >
<!ELEMENT quote ( #PCDATA ) >


<!-- Links -->
<!ELEMENT link ( #PCDATA ) >
<!ATTLIST link url CDATA #REQUIRED >

<!-- VarLinks -->
<!ELEMENT varlink ( #PCDATA ) >
<!ATTLIST varlink url CDATA #REQUIRED >
<!ATTLIST varlink varurl CDATA #REQUIRED >


<!ELEMENT xref ( #PCDATA ) >
<!ATTLIST xref chapter IDREF #IMPLIED >
<!ATTLIST xref section NMTOKEN #IMPLIED >


<!-- Lists -->
<!ELEMENT ol ( li+ ) >
<!ELEMENT ul ( li+ ) >

<!ELEMENT li ( %inline; | codeblock | p | ol )* >

<!ELEMENT itemtable ( item+ ) >
<!ATTLIST itemtable labeld CDATA "Value" >
<!ATTLIST itemtable labelt CDATA "Field" >

<!ELEMENT item ( itemt, itemd ) >
<!ELEMENT itemt ( %inline; )* >
<!ELEMENT itemd ( %block; )* >

=== fink/website/xml/advanced/advanced.pt.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document SYSTEM "../finkdoc.dtd">
<document filename="index" lang="pt">
  <title>Tópicos avançados do Fink</title>
  <shorttitle>Avançado</shorttitle>
  <cvsid>$Id: advanced.pt.xml,v 1.4 2023/08/04 5:08:13 nieder Exp $</cvsid>

  <preface>
    <p>Este documento descreve tópicos avançados que não estão presentes no
    <link url="/doc/users-guide/">Guia do
    usuário</link>.</p>
  </preface>

  <chapter filename="bindist">
    <title>Rodando seu próprio servidor de distribuição de binários</title>
    <shorttitle>Servidor de Distr. de Binários</shorttitle>

    <section name="intro">
      <title>Introdução</title>

      <p>Esta seção descreve um método para grupos de trabalho com mais de uma
      instalação do Fink para que usem um servidor central de compilação
      ("mestre") que distribui pacotes binários para todos os clientes no
      grupo.</p>

      <p>O método é composto pelos seguintes passos no <xref
      section="master">servidor "mestre"</xref> e nas <xref
      section="client">máquinas clientes</xref>:</p>
    </section>

    <section name="master">
      <title>Passos a serem executados no servidor "mestre"</title>

      <ol>
        <li>
          Instale o Fink em <filename>/opt/sw</filename> (diretório padrão, use um
          link simbólico se for necessário).
        </li>

        <li>
            Compile os pacotes da forma habitual. Eles não precisam estar
            necessariamente instalados, mas apenas compilados.
        </li>

        <li>
          <p>Execute o comando <code>fink scanpackages</code> sempre que o seu
          conjunto de pacotes compilados for alterado. Isto faz com que o fink
          gere os índices apt para todas as árvores habilitadas.</p>

          <p>De forma alternativa, você pode executar o comando <code>fink
          cleanup</code> que irá limpar todos os pacotes binários e de códigos
          fontes. O comando <code>fink scanpackages</code> pode ser chamado
          após o processo de limpeza.</p>
        </li>

        <li>
          Inicie um servidor Web. Por exemplo, habilite o "Compartilhamento Web
          Pessoal" na seção Compartilhamento das Preferências do Sistema.
          Configure então o httpd para publicar seu diretório
          <filename>/opt/sw/fink</filename> através da adição das seguintes linhas
          ao seu arquivo <filename>/etc/httpd/httpd.conf</filename>:

          <codeblock>Alias /fink /opt/sw/fink
&lt;Directory /opt/sw/fink&gt;
  Options Indexes FollowSymLinks
&lt;/Directory&gt;</codeblock>
        </li>

        <li>
          Execute o comando <code>sudo /usr/sbin/apachectl graceful</code> para
          (re)iniciar seu servidor Web.
        </li>
      </ol>

      <p>Lembre-se de executar novamente o comando <code>fink
      scanpackages</code> (ou <code>fink cleanup</code>) sempre que
      compilar/atualizar pacotes no servidor "mestre" para que eles fiquem
      disponíveis para suas máquinas remotas.</p>

      <p><em>Observações:</em></p>

      <p>Você também pode criar um usuário 'fink' e adicionar as linhas acima
      ao arquivo <filename>/etc/httpd/users/fink.conf</filename>.</p>

      <p>Se você usa o pacote apache2 do Fink, ajuste os diretórios acima de
      forma correspondente.</p>
    </section>

    <section name="client">
      <title>Passos a serem executados nas máquinas clientes</title>

      <ol>
        <li>
          Instale o Fink no diretório <filename>/opt/sw</filename> (diretório
          padrão).
        </li>

        <li>
          Execute o comando <code>fink configure</code> e habilite a opção para
          baixar pacotes da distribuição de binários.  ("UseBinaryDist: true"
          no arquivo <filename>/opt/sw/etc/fink.conf</filename>).
        </li>

        <li>
          Edite o arquivo <filename>/opt/sw/etc/apt/sources.list</filename> e
          adicione as linhas que representam suas árvores do Fink. Por exemplo,
          se o endereço IP do servidor mestre for 192.168.42.7, você deve
          adicionar:

          <codeblock>deb http://192.168.42.7/fink stable main crypto
deb http://192.168.42.7/fink unstable main crypto
deb http://192.168.42.7/fink local main</codeblock>
        </li>

        <li>
          Execute o comando <code>fink selfupdate</code>. Você deverá ver algo
          parecido com:

          <codeblock>...
Hit http://192.168.42.7 stable/main Packages
Hit http://192.168.42.7 stable/main Release
Hit http://192.168.42.7 stable/crypto Packages
...</codeblock>

          ao fim do processo de atualização (caso o nível de quantidade de
          informações seja &gt;= 1).
        </li>
      </ol>

      <p>Quando os comandos <code>fink update-all</code> ou <code>fink install
      &lt;package&gt;</code> forem executados, eles irão baixar os pacotes
      necessários do servidor "mestre" caso estejam disponíveis.</p>
    </section>

    <section name="remarks">
      <title>Observações</title>

      <ul>
        <li>
          Seu servidor "mestre" precisa usar a versão mais antiga do X11 dentre
          as que são usadas em todos os clientes, ou seja, se alguma das
          máquinas clientes usa o X11 da Apple, o servidor "mestre" também
          precisa usá-lo.
        </li>

        <li>
          Para salvar espaço em disco na máquina "mestre", você pode remover
          pacotes que sejam apenas dependências de compilação (ou seja, que não
          sejam necessários para executar algo). O pacote
          <code>debfoster</code> provê uma boa forma de fazer isto. Tenha
          cuidado para não remover pacotes essenciais como o <code>apt</code>.
        </li>
      </ul>

      <p>Esta documentação foi parcialmente adaptada do documento <link
      url="http://ranger.befunk.com/blog/archives/000258.html">"Sharing the
      Fink"</link> escrito por RangerRick. Obrigado!</p>
    </section>
  </chapter>
</document>

=== fink/website/xml/fink-readme/readme.pt.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="readme" lang="pt">
<title>Leia-me do Fink</title>
<shorttitle>Leia-me</shorttitle>
<cvsid>$Id: readme.pt.xml,v 1.2 2012/11/11 15:20:15 gecko2 Exp $</cvsid>

<preface>
  <p>Este é o Fink, um sistema de gerenciamento de pacotes cujo objetivo é
  trazer todo o mundo do software de código aberto ao Darwin e ao Mac OS X.</p>

  <p>Com a ajuda do dpkg, o Fink mantém uma hierarquia de diretórios separada.
  Ele baixa versões originais de códigos fontes, faz ajustes caso necessário,
  configura-os para o Darwin, compila-os e os instala. As informações sobre
  pacotes disponíveis e ajustes necessários (as "descrições de pacotes") são
  mantidas em separado mas são geralmente incluídas com esta distribuição. O
  código fonte em si é baixado da Internet quando necessário.</p>

  <p>Apesar de o Fink ainda não poder ser considerado "maduro" e ter alguns
  ajustes a fazer e funcionalidades a implementar, ele é usado com sucesso por
  um grande número de pessoas. Por favor, leia as instruções cuidadosamente e
  não se surpreenda caso algo não funcione conforme esperado. Há boas
  explicações para a maior parte das falhas; veja o site caso necessite de
  ajuda.</p>

  <p>O Fink é distribuído conforme os termos da licença GPL da GNU. Veja
  o arquivo COPYING para mais detalhes.</p>
</preface>

<section name="req"><title>Requisitos</title>
  <p>Você precisa de:</p>

  <ul>
    <li><p>Um sistema Mac OS X instalado, versão 10.4 ou mais recente. É
    possível que funcione no Darwin 8.0 mas isto não foi testado. Versões
    anteriores de ambos <em>não</em> funcionarão.</p></li>

    <li><p>Ferramentas de desenvolvimento. No Mac OS X, instale o pacote
    XcodeTools.pkg da mídia de instalação. Assegure-se de que as ferramentas
    que você instalar são apropriadas para sua versão do Mac OS X. No Darwin,
    as ferramentas deveriam ser instaladas por padrão.</p></li>

    <li><p>Acesso à Internet. Todo código fonte é baixado de sites
    espelhos.</p></li>

    <li><p>Paciência. Compilar vários pacotes grandes leva tempo: horas ou até
    mesmo dias.</p></li>
  </ul>
</section>

<section name="install"><title>Instalação</title>
  <p>O processo de instalação é descrito em detalhes no arquivo INSTALL. Por
  favor, leia-o primeiro; o processo não é trivial. O arquivo também descreve o
  procedimento de atualização.</p>
</section>

<section name="usage"><title>Usando o Fink</title>
  <p>O arquivo USAGE descreve como configurar seus caminhos e como instalar e
  remover pacotes. Também possui uma lista completa dos comandos
  disponíveis.</p>
</section>

<section name="questions"><title>Outras perguntas?</title>
  <p>Se a documentação aqui incluída não responder sua pergunta, visite o site
  do Fink em <link
  url="/">/</link> e
  consulte a página de Ajuda: <link
  url="/help/">/help/</link>.
  Ela indicará outros documentos que estão disponíveis e onde procurar por
  ajuda caso precise.</p>

  <p>Se você gostaria de contribuir algo ao Fink, a página de Ajuda mencionada
  acima também contém uma lista de coisas que você pode fazer como testar ou
  criar pacotes.</p>
</section>

<section name="uptodate"><title>Mantendo-se informado</title>
  <p>O site do projeto está localizado em <link
  url="/">/</link>.</p>

  <p>Para ser informado de novos lançamentos, vá à página <link
  url="/lists/fink-announce.php">https://www.finkproject.org/lists/fink-announce.php</link>
  e assine a lista de discussão fink-announce. Esta lista é moderada e possui
  baixo tráfego.</p>
</section>

</article>

=== fink/website/xml/usage/usage.en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="index" lang="en" fsroot="../../">
<title>Fink Usage</title>
<shorttitle>Usage</shorttitle>
<cvsid>$Id: usage.xml,v 1.17 2023/08/04 5:20:38 nieder Exp $</cvsid>

<section><title>Setting The Paths</title>
<p>
To use the software installed in Fink's directory hierarchy, including
the fink command itself, you must set your PATH environment variable
(and some others) accordingly.
Shell scripts are provided to do this for you.
If you use tcsh, add the following to your .cshrc:
</p>
<codeblock>source /opt/sw/bin/init.csh</codeblock>
<p>
Editing .cshrc will only affect new shells (i.e. newly opened Terminal
windows), so you should also run this command in all Terminal windows
that you opened before you edited the file.
You'll also need to run <code>rehash</code> because tcsh caches the
list of available commands internally.
</p>
<p>
If you use a Bourne type shell (e.g. sh, bash, zsh), use instead:
</p>
<codeblock>source /opt/sw/bin/init.sh</codeblock>
<p>
Note that the scripts also add /usr/X11R6/bin and /usr/X11R6/man to
your path so you can use X11 when it is installed.
Packages have the ability to add settings of their own, e.g. the qt
package sets the QTDIR environment variable.
</p>
</section>

<section><title>Using Fink</title>
<p>Fink has several commands that work on packages. All of them need at
least one package name, and all can handle several package names at
once. You can specify just the package name (e.g. gimp), or a fully
qualified name with a version number (e.g. gimp-1.2.1 or
gimp-1.2.1-3). Fink will automatically choose the latest available
version and revision when they are not specified.</p>
<p>What follows is a list of commands that Fink understands:</p>
</section>

<section><title>install</title>
<p>The install command is used to install packages. It downloads,
configure, builds and installs the packages you name. It will also
install required dependencies automatically, but will ask you for
confirmation before it does so. Example:</p>
<codeblock>fink install nedit

Reading package info...
Information about 131 packages read.
The following additional package will be installed:
 lesstif
Do you want to continue? [Y/n]</codeblock>
<p>Aliases for the install command: update, enable, activate, use. (Most
of these for historic reasons.)</p>
</section>

<section><title>remove</title>
<p>The remove command removes packages from the system by calling 'dpkg
--remove'. The current implementation has some flaws: It only works on
packages Fink knows about (i.e. where an .info file is present); and it
doesn't check dependencies itself but rather completly leaves that to
the dpkg tool (usually this poses no problem, though).</p>
<p>The remove command only removes the actual package files, but leaves
the .deb compressed package file intact. This means that you can
re-install the package later without going through the compile process
again. If you need the disk space, you can remove the .deb from the
/opt/sw/fink/dists tree.</p>
<p>Aliases: disable, deactivate, unuse, delete, purge.</p>
</section>

<section><title>update-all</title>
<p>This command updates all installed packages to the latest version. It
does not need a package list, so you just type:</p>
<codeblock>fink update-all</codeblock>
</section>

<section><title>list</title>
<p>
This command produces a list of available packages, listing
installation status, the latest version and a short description.
If you call it without parameters, it will list all available
packages.
You can also pass a name or a shell pattern, and fink will list all
packages that match.
</p>
<p>
The first column displays the installation state with the following
meanings:
</p>
<codeblock>     not installed
 i   latest version is installed
(i)  installed, but a newer version is available</codeblock>
<p>
Some usage examples:
</p>
<codeblock>fink list            - list all packages
fink list bash       - check if bash is available and what version
fink list &quot;gnome*&quot;   - list all packages that start with 'gnome'</codeblock>
<p>
The quotes in the last example are necessary to stop the shell from
interpreting the pattern itself.
</p>
</section>

<section><title>describe</title>
<p>
This command displays a description of the package you name on the
command line.
Note that only a small part of the packages currently have a
description.
</p>
<p>
Aliases: desc, description, info
</p>
</section>

<section><title>fetch</title>
<p>Downloads the named packages, but does not install it. This command
will download the tarballs even if they were downloaded before.</p>
</section>

<section><title>fetch-all</title>
<p>Downloads <em>all</em> package source files. Like fetch, this downloads the
tarballs even when they were downloaded before.</p>
</section>

<section><title>fetch-missing</title>
<p>Downloads <em>all</em> package source files. This command will only download
files that are not present on the system.</p>
</section>

<section><title>build</title>
<p>Builds a package, but does not install it. As usual, the source
tarballs are downloaded if they can not be found. The result of this
command is an installable .deb package file, which you can quickly
install later with the install command. This command will do nothing
if the .deb already exists. Note that dependencies are still
<em>installed</em>, not just built.</p>
</section>

<section><title>rebuild</title>
<p>Builds a package (like the build command), but ignores and overwrites
the existing .deb file. If the package is installed, the newly created
.deb file will also be installed in the system via dpkg. Very useful
during package development.</p>
</section>

<section><title>reinstall</title>
<p>Same as install, but will install the package via dpkg even when it is
already installed. You can use this when you accidentally deleted
package files or changed configuration files and want to get the
default settings back.</p>
</section>

<section><title>configure</title>
<p>
Reruns the Fink configuration process.
This will let you change your mirror sites and proxy settings, among
others.
</p>
</section>

<section><title>selfupdate</title>
<p>
This command automates the process of upgrading to a new Fink
release.
It checks the Fink website to see if a new version is available.
It then downloads the package descriptions and updates the core
packages, including fink itself.
This command can only upgrade to regular releases, but you can use it
to upgrade from a CVS version to a later regular release.
It will refuse to run if you have /opt/sw/fink set up to get package
descriptions directly from CVS.
</p>
</section>

<section><title>Further Questions</title>
<p>
If your questions are not answered by this document, read the FAQ at
the Fink website:
<link url="/faq/">/faq/</link>.
If that still doesn't answer your questions, subscribe to the
fink-users mailing list via <link
url="/lists/fink-users.php">/lists/fink-users.php</link>
and ask there.
</p>
</section>

</article>

=== fink/website/xml/advanced/advanced.de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document SYSTEM "../finkdoc.dtd">
<document filename="index" lang="de">
  <title>Fortgeschrittene Fink Themen</title>
  <shorttitle>Fortgeschrittenes</shorttitle>
  <cvsid>$Id: advanced.de.xml,v 1.2 2023/08/04 5:08:13 nieder Exp $</cvsid>
  <preface>
    <p>
Diese Dokument beschreibt fortgeschrittene Themen, die nicht im
<link url="/doc/users-guide/">User's Guide</link> beschrieben werden.
    </p>
  </preface>
  <chapter filename="bindist">
    <title>Betrieb eines eigenen Servers für eine binäre Distribution</title>
    <shorttitle>Binärer Distro Server</shorttitle>
    <section name="intro">
      <title>Einführung</title>
      <p>
Dieser Abschnitt beschreibt eine Methode für Arbeitsgruppen mit mehreren
Fink Installationen, bei der ein zentraler Build-Server (der Master)
benutzt wird, der die binären Pakete an alle Klienten der Gruppe verteilt.
      </p>
      <p>
Die Methode erfordert die folgenden Schritte auf dem
<xref section="master">"Master"-Server</xref> und den
<xref section="client">Klienten-Rechnern</xref>:
      </p>
    </section>
    <section name="master">
      <title>Schritte auf dem "Master"-(Build)-Server</title>
      <ol>
        <li>
Installieren sie Fink unter <filename>/opt/sw</filename> (Der voreingestellte
Basis-Pfad; wenn erforderlich, einen Symlink verwenden).
        </li>
        <li>
Pakete wie üblich erstellen. Sie müssen nicht unbedingt installiert
werden, erstellen reicht aus.
        </li>
        <li>
          <p>
Führen sie das Kommando <code>fink scanpackages</code> aus, wenn sich ihr
Satz an erstellten Paketen geändert hat. Dadurch erstellt Fink die
apt-Indizes für alle eingeschalteten Bäume (trees) neu.
          </p>
          <p>
Alternativ können sie auch das Kommando <code>fink cleanup</code>
ausführen. Dieses entfernt alle obsoleten Quell- und Binär-Pakete. Am Ende
des Entfernens wird auch das Kommando <code>scanpackages</code>
ausgeführt.
          </p>
        </li>
        <li>
Starten sie einen Webserver: z.B. schalten sie "Personal Web Sharing" in
der Kategorie "Freigaben" in den Systemeinstellungen ein. Richten sie
dann httpd ein, dass es ihr Verzeichnis <filename>/opt/sw/fink</filename> zur
Verfügung stellt, in dem sie folgende Zeilen in der Datei
<filename>/etc/httpd/httpd.conf</filename> hinzufügen:
          <codeblock>
Alias /fink /opt/sw/fink
&lt;Directory /opt/sw/fink&gt;
  Options Indexes FollowSymLinks
&lt;/Directory&gt;
          </codeblock>
        </li>
        <li>
Führen sie dann das Kommando <code>sudo /usr/sbin/apachectl graceful</code> 
aus, um den Webserver (neu) zu starten.
        </li>
      </ol>
      <p>
Bitte denken sie daran, das Kommando <code>fink scanpackages</code> (oder
<code>fink cleanup</code>) immer dann erneut auszuführen, wenn sie Pakete
auf dem "Master"-Server neu erstellt oder aktualisiert haben, damit sie den
Klienten-Rechnern zur Verfügung gestellt werden.
      </p>
      <p>
<em>Notizen:</em>
      </p>
      <p>
Sie sollten auch einen Nutzer 'fink' erstellen und die folgende Zeile in
der Datei <filename>/etc/httpd/users/fink.conf</filename> hinzufügen.
      </p>
      <p>
Sollten sie das Paket apache2 aus Fink benutzen, müssen sie die Pfade
entsprechend anpassen.
      </p>
    </section>
    <section name="client">
      <title>Schritte auf den Klienten-Rechnern</title>
      <ol>
        <li>
Installieren sie Fink unter <filename>/opt/sw</filename> (voreingestellter
Basis-Pfad).
        </li>
        <li>
Führen sie das Kommando <code>fink configure</code> aus und schalten sie
die Option ein, die Pakete aus einer binären Distribution zu beziehen.
("UseBinaryDist: true" in der Datei <filename>/opt/sw/etc/fink.conf</filename>.)
        </li>
        <li>
Editieren sie die Datei <filename>/opt/sw/etc/apt/sources.list</filename> und
fügen sie die Zeilen dazu, die ihren Fink-Baum repräsentieren. Wenn zum
Beipsiel die IP-Adresse ihres Build-Servers 192.168.42.7 lautet, müssen sie
folgendes hinzufügen:
          <codeblock>
deb http://192.168.42.7/fink stable main crypto
deb http://192.168.42.7/fink unstable main crypto
deb http://192.168.42.7/fink local main
          </codeblock>
        </li>
        <li>
Führen sie das Kommando <code>fink selfupdate</code> aus. Sie sollten
am Ende der Aktualisierung (wenn das "verbose"-Level &gt;= 1 ist)
etwas in der Art sehen:
          <codeblock>
...
Hit http://192.168.42.7 stable/main Packages
Hit http://192.168.42.7 stable/main Release
Hit http://192.168.42.7 stable/crypto Packages
...
          </codeblock>
        </li>
      </ol>
      <p>
Führt man das Kommando <code>fink update-all</code> oder <code>fink
install &lt;package&gt;</code> aus, werden alle benötigten Pakete falls
vorhanden in binärer Form vom "Master"-Server bezogen.
      </p>
    </section>
    <section name="remarks">
      <title>Bemerkungen</title>
      <ul>
        <li>
Ihr "Master"-Server muss die niedrigste Version von X11 benutzen, die auf
einem ihrer Klienten-Rechner installiert ist. Mit anderen Worten: Benutzt
einer ihrer Klienten-Rechner Apples X11, muss auch ihr "Master"-Server
Apples X11 benutzen.
        </li>
        <li>
Will man Platz auf dem Build-Server sparen, kann man alle Pakete
entfernen, die lediglich Build-Abhängigkeiten sind (d.h. sie werden nicht
für das Laufen des Programms benötigt). Das Paket <code>debfoster</code>
ermöglicht dies in schöner Form. Bitte achten sie darauf, keine
essentiellen Pakete wie z. B. <code>apt</code> zu löschen.
        </li>
       </ul>
      <p>
Diese Dokumentation ist teilweise adaptiert von
<link url="http://ranger.befunk.com/blog/archives/000258.html">"Sharing the Fink"</link>
von RangerRick. Vielen Dank!
      </p>
    </section>
  </chapter>
</document>
