=== fink/website/xml/finkdoc.dtd
<!ENTITY % block "codeblock | ol | p | ul" >
<!ENTITY % inline "#PCDATA | code | strong | em | filename | link | varlink | tt | quote | xref" >

<!ENTITY fink_version "0.9.0" >
<!ENTITY fink_tool_version "0.45.4">


<!-- Root elements -->
<!ELEMENT article ( title, shorttitle, cvsid, preface?, section+ ) >
<!ATTLIST article filename ID #REQUIRED >
<!ATTLIST article lang CDATA "en" >
<!ATTLIST article fsroot CDATA "../" >

<!ELEMENT document ( title, shorttitle, cvsid, preface?, chapter+ ) >
<!ATTLIST document filename ID #REQUIRED >
<!ATTLIST document lang CDATA "en" >
<!ATTLIST document section CDATA "documentation" >
<!ATTLIST document fsroot CDATA "../../" >


<!-- Structure -->
<!ELEMENT chapter ( title, shorttitle, preface?, section+ ) >
<!ATTLIST chapter filename ID #REQUIRED >

<!ELEMENT title ( #PCDATA ) >
<!ELEMENT shorttitle ( #PCDATA ) >
<!ELEMENT cvsid ( #PCDATA ) >
<!ELEMENT preface ( p+ ) >

<!ELEMENT section (title?, ( %block; | itemtable )*) >
<!ATTLIST section name NMTOKEN #IMPLIED >
<!ATTLIST section translated (yes|no) "yes" >


<!-- Block elements -->
<!ELEMENT codeblock ( #PCDATA | em | strong )* >
<!ELEMENT p ( %inline; )* >
<!ATTLIST p translated (yes|no) "yes" >


<!-- Inline -->
<!ELEMENT code ( #PCDATA | em | strong )* >
<!ELEMENT em ( #PCDATA ) >
<!ELEMENT strong ( #PCDATA ) >
<!ELEMENT filename ( #PCDATA ) >
<!ELEMENT tt ( #PCDATA ) >
<!ELEMENT quote ( #PCDATA ) >


<!-- Links -->
<!ELEMENT link ( #PCDATA ) >
<!ATTLIST link url CDATA #REQUIRED >

<!-- VarLinks -->
<!ELEMENT varlink ( #PCDATA ) >
<!ATTLIST varlink url CDATA #REQUIRED >
<!ATTLIST varlink varurl CDATA #REQUIRED >


<!ELEMENT xref ( #PCDATA ) >
<!ATTLIST xref chapter IDREF #IMPLIED >
<!ATTLIST xref section NMTOKEN #IMPLIED >


<!-- Lists -->
<!ELEMENT ol ( li+ ) >
<!ELEMENT ul ( li+ ) >

<!ELEMENT li ( %inline; | codeblock | p | ol )* >

<!ELEMENT itemtable ( item+ ) >
<!ATTLIST itemtable labeld CDATA "Value" >
<!ATTLIST itemtable labelt CDATA "Field" >

<!ELEMENT item ( itemt, itemd ) >
<!ELEMENT itemt ( %inline; )* >
<!ELEMENT itemd ( %block; )* >

=== fink/website/xml/usage/usage.de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="index" lang="de" fsroot="../../">
<title>Fink Nutzung</title>
<shorttitle>Nutzung</shorttitle>
<cvsid>$Id: usage.xml,v 1.17 2023/08/04 5:20:38 nieder Exp $</cvsid>

<section><title>Pfade setzen</title>
<p>
Damit man die Programme, die in Finks Verzeichnis-Hierarchie installiert sind,
und auch fink selbst benutzen kann muss die Umgebungvariable PATH (und einige
andere) entsprechend gesetzt werden.
Dies wird für sie mit Shell-Skripts erledigt.
Benutzen sie die Shell tcsh, fügen sie folgendes in die Datei .cshrc ein:
</p>
<codeblock>source /opt/sw/bin/init.csh</codeblock>
<p>
Änderungen in der Datei .cshrc wirken sich nur bei einer neuen Shell aus (d. h.
in einem neu geöffneten Terminalfenster). Deshalb sollten sie das Kommando auch
in jedem Terminalfenster ausführen, das sie öffneten, bevor sie die Datei
editierten.
Sie müssen auch das Kommando <code>rehash</code>, weil die Shell tcsh die Liste
der vorhandenen Kommmando intern zwischenspeichert.
</p>
<p>
Nutzen wie eine Art Bourne shell (z. B. sh, bash, zsh) führen sie statt dessen
folgendes Kommando aus:
</p>
<codeblock>source /opt/sw/bin/init.sh</codeblock>
<p>
Anmerkung: Die Skripte fügen auch /usr/X11R6/bin und /usr/X11R6/man zu ihrem
Pfad hinzu, so dass sie X11 benutzen können, falls installiert.
Pakete können ihrerseits eigene Einstellungen vornehmen. Das Paket qt fügt zum
Beispiel die Umgebungsvariable QTDIR hinzu.
</p>
</section>

<section><title>Fink benutzen</title>
<p>
Fink hat mehrere Kommandos um Pakete zu bearbeiten. Alle brauchen mindestens
einen Paketnamen, können aber auch mehrere Pakete auf einmal bearbeiten. Sie
können den einfachen Paketnamen (z. B. gimp) angeben oder den vollständig
spezifizierten mit Versionsnummer (z.B. gimp-1.2.1 oder gimp-1.2.1-3). Fink
wird automatisch die jeweils letzte Version und Revision auswählen, wenn keine
angegeben ist.
</p>
<p>
Im folgenden werden die Kommandos aufgelistet, die Fink versteht:
</p>
</section>

<section><title>install</title>
<p>
Mit dem Kommando install installiert man Pakete. Es lädt das Paket herunter,
konfiguriert, übersetzt und installiert es. Es wird auch alle Abhängigkeiten
automatisch installieren, fragt aber zur Bestätigung nach. Beispiel:
</p>
<codeblock>fink install nedit

Reading package info...
Information about 131 packages read.
The following additional package will be installed:
 lesstif
Do you want to continue? [Y/n]</codeblock>
<p>
Aliase für das Kommando install: update, enable, activate und use.
(Hauptsächlich aus historischen Gründen.)
</p>
</section>

<section><title>remove</title>
<p>
Das Kommando remove löscht Pakete aus dem System, in dem das Kommando
'dpkg --remove' ausgeführt wird. Derzeit gibt es einige Haken: Es funktioniert
für Pakete, die Fink bekannt sind (d. h. das eine Datei .info vorhanden ist) und
es überprüft selbst keine Abhängigkeiten, sondern überlässt dies alles dem Tool
dpkg. Normalerweise ergeben sich jedoch daraus keine Probleme.
</p>
<p>
Das Kommando remove löscht nur die installierten Dateien des Pakets, lässt aber
die komprimierte Paketdatei .deb intakt. Das heißt, dass sie das Paket später
erneut installieren können ohne erneut durch den Übersetzungsprozess gehen zu
müssen. Wird Plattenplatz benötigt, können sie die .deb-Dateien im
Verzeichnisbaum /opt/sw/fink/dists löschen.
</p>
<p>
Aliase für das Kommando remove: disable, deactivate, unuse, delete und purge.
</p>
</section>

<section><title>update-all</title>
<p>
Das Kommando update-all aktualisiert alle Pakete auf die neueste Version. Es
benötigt keine Liste der Pakete. Tippen sie einfach:
</p>
<codeblock>fink update-all</codeblock>
</section>

<section><title>list</title>
<p>
Das Kommando list erzeugt eine Liste aller verfügbaren Pakete, ihren
Installations-Status, die aktuelle Version und eine kurze Beschreibung.
Ohne weitere Parameter listet es alle Pakete auf.
Sie können auch einen Namen oder ein Shellmuster angeben. Fink wird dann nur die
Pakete auflisten, die dazu passen.
</p>
<p>
In der ersten Spalte steht der Installations-Status, mit folgenden Bedeutungen
The first column displays the installation state with the following
meanings:
</p>
<codeblock>     nicht installiert
 i   die aktuelle Version ist installiert
(i)  installiert, es gibt aber eine neuere Version</codeblock>
<p>
Einige Beispiele:
</p>
<codeblock>fink list            - liste alle Pakete auf
fink list bash       - überprüfe die Verfügbarkeit von bash und dessen Version
fink list &quot;gnome*&quot;   - liste alle Pakete auf, deren Namen mit 'gnome' beginnt</codeblock>
<p>
Die Anführungszeichen im letzten Beispiel werden benötigt, damit die Shell das
Muster nicht selbst interpretiert.
</p>
</section>

<section><title>describe</title>
<p>
Das Kommando describe erzeugt die lange Beschreibung des Pakets, dessen Namen
sie in der Kommandozeile angegeben haben.
Beachten sie, dass nicht alle Pakete eine lange Beschreibung haben.
</p>
<p>
Aliase für das Kommando describe: desc, description und info
</p>
</section>

<section><title>fetch</title>
<p>
Das Kommando fetch lädt die angegebenen Pakete herunter, installiert sie aber
nicht. Ist ein Tarballs bereits vorhanden, wird in einem Dialog abgefragt, ob
das existierende durch ein frisch herunter geladenes ersetzt werden soll.
</p>
</section>

<section><title>fetch-all</title>
<p>
Das Kommando fetch-all lädt die Quellcode-Dateien für <em>alle</em> Pakete
herunter. Wie beim Kommando fetch wird in einem Dialog abgefragt, ob
existierende Dateien durch frisch herunter geladene ersetzt werden sollen.
</p>
</section>

<section><title>fetch-missing</title>
<p>
Das Kommando fetch-missing lädt die Quellcode-Dateien für <em>alle</em> Pakete
herunter, die noch nicht vorhanden sind.
</p>
</section>

<section><title>build</title>
<p>
Das Kommando build erzeugt ein Paket, installiert es aber nicht. Wie üblich
werden Quellcode-Dateien herunter geladen, wenn sie nicht gefunden werden.
Das Ergebnis dieses Kommandos ist eine installierbare .deb-Paketdatei, die man
später schnell mit dem Kommando install installieren kann. Existiert die
.deb-Paketdatei bereits, passiert nichts. Beachten sie, dass Abhängigkeiten
nicht nur erzeugt sondern <em>installiert</em> werden.
</p>
</section>

<section><title>rebuild</title>
<p>
Das Kommando rebuild erzeugt ein Paket wie das Kommando build. Es ignoriert und
überschreibt aber eine existierende .deb-Paketdatei. Ist das Paket installiert,
wird die neue .deb-Paketdatei im System mit dpkg installiert. Das Kommando
rebuild ist bei der Entwicklung von Paketen sehr nützlich.
</p>
</section>

<section><title>reinstall</title>
<p>
Das Kommando reinstall installiert ein Paket wie das Kommando install mittels
dpkg, aber auch wenn es bereits installiert ist. Das ist vor allem dann nützlich,
wenn man aus Versehen Paketdateien gelöscht oder Konfigurationsdateien geändert
hat und die Voreinstellung wieder zurück haben möchte.
</p>
</section>

<section><title>configure</title>
<p>
Das Kommando configure startet den Konfigurationsprozess für Fink erneut.
Unter anderem kann man so die Einstellungen für Spiegelserver und Proxy ändern.
</p>
</section>

<section><title>selfupdate</title>
<p>
Das Kommando selfupdate automatisiert das Aktualisieren auf eine neue Version
von Fink.
Es sieht auf der Webseite von Fink nach, ob es eine neuere Version gibt.
Dann lädt es die Paketbeschreibungen herunter und aktualisiert die zentralen
Kernpakete, einschließlich fink selbst.
Mit diesem Kommando kann man nur auf reguläre Versionen aktualisieren. Sie
können es aber verwenden, um von einer cvs-Version auf eine spätere reguläre
Version zu aktualisieren. Es wird sich weigern, abzulaufen, wenn sie /opt/sw/fink so
aufgesetzt haben, dass es Paketbeschreibungen direkt von CVS herunter lädt.
</p>
</section>

<section><title>Weitere Fragen</title>
<p>
Haben sie weitere Fragen, die in diesem Dokument nicht beantwortet wurden, lesen
sie bitte die FAG auf der Fink-Webseite:
<link url="/faq/">/faq/</link>.
Sollte dies ihre Frage immer noch nicht beantworten, abonnieren sie die
Email-Liste für Fink-Nutzer
<link url="/lists/fink-users.php">/lists/fink-users.php</link>
und fragen sie dort.
</p>
</section>

</article>

=== fink/website/xml/advanced/advanced.en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document SYSTEM "../finkdoc.dtd">
<document filename="index" lang="en">
  <title>Advanced Fink Topics</title>
  <shorttitle>Advanced</shorttitle>
  <cvsid>$Id: advanced.en.xml,v 1.7 2023/08/04 5:08:13 nieder Exp $</cvsid>
  <preface>
    <p>
This document describes advanced topics not found in the
<link url="/doc/users-guide/">User's Guide</link>.
    </p>
  </preface>
  <chapter filename="bindist">
    <title>Running your own Binary Distribution Server</title>
    <shorttitle>Binary Distro Server</shorttitle>
    <section name="intro">
      <title>Introduction</title>
      <p>
This section describes a method for workgroups of more than one Fink
installation to use a central build server ("master") that distributes binary
packages to all clients in the group.
      </p>
      <p>
The method involves the following steps on the 
<xref section="master">"master" server</xref> and on the
<xref section="client">client machines</xref>:
      </p>
    </section>
    <section name="master">
      <title>Steps on "master" (build) server</title>
      <ol>
        <li>
Install Fink at <filename>/opt/sw</filename> (default basepath, use a
symlink if necessary).
        </li>
        <li>
Build packages as usual. They don't necessarily have to be installed, just
built.
        </li>
        <li>
          <p>
Run <code>fink scanpackages</code> whenever your set of built
packages has changed. This will make fink generate apt indexes for all of your
enabled trees.
          </p>
          <p>
As an alternative you could run <code>fink cleanup</code> which will
clean all obsolete src and binary packages. <code>scanpackages</code>
will be called at the end of the cleaning process.
          </p>
        </li>
        <li>
Start a web server:  E.g. enable "Personal Web Sharing" in the Sharing section
of System Preferences. Then set up httpd to serve your <filename>/opt/sw/fink</filename>
directory by adding the following lines to your
<filename>/etc/httpd/httpd.conf</filename> file. 
          <codeblock>
Alias /fink /opt/sw/fink
&lt;Directory /opt/sw/fink&gt;
  Options Indexes FollowSymLinks
&lt;/Directory&gt;
          </codeblock>
        </li>
        <li>
Run <code>sudo /usr/sbin/apachectl graceful</code> to (re)start your
web server.
        </li>
      </ol>
      <p>
Remember to re-run <code>fink scanpackages</code> (or <code>fink
cleanup</code>) whenever you build/update packages on the "master"
server to make them available to your remote machines.
      </p>
      <p>
<em>Notes:</em>
      </p>
      <p>
You could also create a user 'fink' and add the above lines to 
<filename>/etc/httpd/users/fink.conf</filename>.
      </p>
      <p>
If you use the apache2 package from Fink adjust the paths above accordingly.
      </p>
    </section>
    <section name="client">
      <title>Steps on client machines</title>
      <ol>
        <li>
Install Fink at <filename>/opt/sw</filename> (default basepath).
        </li>
        <li>
Run <code>fink configure</code> and enable the option to download
packages from the binary distribution. ("UseBinaryDist: true" in the
<filename>/opt/sw/etc/fink.conf</filename> file.)
        </li>
        <li>
Edit <filename>/opt/sw/etc/apt/sources.list</filename>, and add the lines
representing your Fink trees. For example, if the IP address of your build box
is 192.168.42.7, you need to add:
          <codeblock>
deb http://192.168.42.7/fink stable main crypto
deb http://192.168.42.7/fink unstable main crypto
deb http://192.168.42.7/fink local main
          </codeblock>
        </li>
        <li>
Run <code>fink selfupdate</code>. You should see something like:
          <codeblock>
...
Hit http://192.168.42.7 stable/main Packages
Hit http://192.168.42.7 stable/main Release
Hit http://192.168.42.7 stable/crypto Packages
...
          </codeblock>
towards the end of the update process (if the verbose level is &gt;= 1).
        </li>
      </ol>
      <p>
Running <code>fink update-all</code> or <code>fink install
&lt;package&gt;</code> will now download the necessary packages as
binaries from the "master" server if available.
      </p>
    </section>
    <section name="remarks">
      <title>Remarks</title>
      <ul>
        <li>
Your "master" server needs to use the lowest version of X11 that you're using
on all of the clients, i.e. if any of the client machines uses Apple's X11, the
"master" server must use it too.</li>
        <li>In order to save space on your build machine, you can remove packages that are only build-dependencies (i.e. not needed to run anything).  The <code>debfoster</code> package provides a nice way to do this. Be careful not to remove essential packages, such as <code>apt</code>. </li>
       </ul>
      <p>
This documentation is adapted in part from
<link url="http://ranger.befunk.com/blog/archives/000258.html">"Sharing the Fink"</link>
by RangerRick. Thanks!
      </p>
    </section>
  </chapter>
</document>

=== fink/website/xml/netiquette/netiquette.es.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../finkdoc.dtd">
<document filename="index" lang="es">
  <title>Como mandar mensajes a las Listas de Correo de Fink</title>
  <shorttitle>Netiquette</shorttitle>
  <cvsid>$Id: netiquette.es.xml,v 1.5 2023/08/04 5:23:15 nieder Exp $</cvsid>
  <preface>
    <p><em>Este es un documento en construcción.</em></p>
    <p>Este documento pretende ser una guía para los nuevos miembros de las Listas de 
    Correo de Fink. La idea principal es indicar a los usuarios como mandar mensajes efectivamente, con el fin de solucionar efectivamente cualquier problema. </p>
    <p>Usted puede haber sido mandado a esta página en respuesta a algún mensaje. Por favor, no se ofenda. Lo más posible es que es necesario que provee más información con el objeto de aclarar la causa de su problema, y que dicha información se encuentre listada aquí.</p>
  </preface>
  <chapter filename="before-post">
    <title>¿Qué hacer antes de 'postear'?</title>
    <shorttitle>Antes de 'Postear'</shorttitle>
    <section name="research">
      <title>Investige su pregunta. </title>
      <p>Siempre es importante hacer algo de investigación antes de postear, dado que es posible que ya se haya dado una respuesta a su pregunta. Algunos ejemplos de los lugares donde buscar son:</p>
      <ul>
        <li>la documentación en línea</li>
        <li>los archivos de la lista de correo</li>
        <li>Google</li>
      </ul>
    </section>
  </chapter>
  <chapter filename="first-post">
    <title>Primer "Post"</title>
    <shorttitle>Inicial</shorttitle>
    <section name="system">
      <title>¿Qué has instalado?</title>
      <p>Si has estado teniendo problemas con un paquete instalado, deberás proveer la siguiente información acerca de tu sistema:</p>
      <ul>
        <li>Tu versión de OS.</li>
        <li>La versión de Fink que estás usando.  Un tip útil es ejecutar el comando <codeblock>fink --version</codeblock>en una ventana de terminal y adicionar el resultado a tu información en el "post".</li>
        <li>También deberás especificar si estas instalando a partir de binarios, e.g. usando <code>apt-get</code>, o de la fuenta, e.g. usando <code>fink install</code>.<p>En el segundo caso, favor de indicar la versión de las Developer Tools que estas usando.</p></li>
        <li><p>Si estas instalando un paquete que requiere de X11, deberás indicar si estas usando:  Apple's X11 o XFree86.  En el segundo caso, especifica la versión.   </p><p>Si tienes dudas, provee toda la informacion arriba mencionada.</p></li>
      </ul>
    </section>
    <section name="problem-description">
      <title>¿Qué es lo que esta mal?</title>
      <ul>
        <li><em>Especifica el nombre y la vbersión del paquete que esta causando 
        problemas.</em>  <p>Este dato debera estar en la línes del tema de tu mensaje.
        </p><p>Esto significa que si estas teniendo problemas con <code>foo-3.141-6
        </code>, no solo reportes un problema con <code>foo</code>.</p><p>En particular,
        si estás instalando un paquete (e.g. <code>baz-2.18-1</code>) que depende de 
        otros paquetes, (<code>foo-3.141-6</code>, <code>bar-16.0-9</code>, ...) , y 
        estás teniendo problemas con <code>foo</code>, deberás reportar un problema con 
        <code>foo-3.141-6</code>, no con <code>baz-2.18-1</code>.</p></li>
        <li><em>Describe el problema.</em>  
        <p>Esto significa que deberás "postear" una muestra del mensaje de error que 
        estes recibiendo.</p><ol>
            <li>En el caso de problemas con la instalación de binarios, comienza
            donde esta siendo desempaquetado en paquete problematico:
            <codeblock>...
Selecting previously deselected package foo
error unpacking foo
...</codeblock>y continua hasta el final.<p></p></li>
            <li>Hay pocas posibilidades de problemas con la instalacion desde la fuente:
            <ol>
                <li>Si el error es durante la configuración inicial, el error ocurrirá 
                desde el principio. "Postea" desde el último grupo de pruebas que se 
                ejecutaron justo antes del mensaje de error hasta después de dicho 
                mensaje:<codeblock>....
Checking for bar-config...no
Error:  bar-config not found
....</codeblock><p>Si crees que el dato puede ayudar, entonces puedes "postear" la sección relevante del log del archivo de configuración, e.g. <filename>/opt/sw/src/foo-3.141-6/foo-3.141/config.log</filename>.  <em>Por favor, no pongas TODO el archivo, podría se bastante grande.</em></p></li>
                <li>O, el error puede aparecer hasta que se inicía la construcción del
                paquete. En este caso, "postea" la última línea que el compilador trato 
                de ejecutar hasta el mensaje de error:<codeblock>...
gcc &lt;flags, files etc.&gt;
&lt;error messages&gt;
...</codeblock></li>
                <li>Sí lo que obtienes es el temido error de <code>execution of mv failed</code> lo que habrás de hacer es buscar en el output del build un error previó,
                 así que mejor buscaló antes de hacer tu "post".</li>
              </ol></li>
          </ol>    </li>
      </ul>
    </section>
    <section name="remedies">
      <title>¿Qué has intentado?</title>
      <p>Es una buena idea mencionar que cosas has intentado para corregir la 
      situación, e.g.</p>
      <ul>
        <li>Instructiones en el FAQ u otra documentación</li>
        <li>La remoción de los paquetes que parecen causar conflicto</li>
        <li>Reconstrucciones/reinstalaciones</li>
        <li>La actualización de las descripciones de los paquetes</li>
        <li>etc.</li>
      </ul>
      <p>De esta manera, nadie empezará a sugerir cosas que ya intentaste.</p>
    </section>
    <section name="future-plans">
      <title>¿Qué intentarás ahora?</title>
      <p>Algunas cosas caen en esta categoría:</p>
      <ul>
        <li>"Postea" lo que planeas hacer en caso de no obtener respuesta inmediata.</li>
        <li>Preguntar acerca de lo apropiado del curso de acción elegido.</li>
      </ul>
    </section>
  </chapter>
  <chapter filename="reply">
    <title>Respondiendo a los "posts"</title>
    <shorttitle>Respondiendo</shorttitle>
    <preface>
      <p>Este capítulo cubre como responder a los "posts".</p>
    </preface>
    <section name="reply-to-list">
      <title>Asegurate de responder a la Lista.</title>
      <p>A diferencia de otras listas a las que estes suscrito, las Listas del Fink
      están ajustadas para que si respondes a un mensaje, la respuesta llega a quien puso el mensaje, pero <em>no</em> a la lista.  Por favor, asegurate de responder a la lista, así:  </p>
      <ul>
        <li>Más gente verá tu problema.</li>
        <li>No monopolizaras el tiempo de nadie. Recuerda que la gente que responde a las listas son voluntarios.</li>
        <li>Otras pueden beneficiarse. El tener un set completo de intercambio de correo a la vista del público significa que este set irá al archivo de la lista de correo y finalmente a la documentación.</li>
      </ul>
      <p>Frecuentemente se usa el comando <quote>Reply to All</quote> para lograr ésto:</p>
      <ul>
        <li>Es igual de facil que ejecutar "Reply".</li>
        <li>Aunque esto manda el mensaje tanto a lista como al autor de mensaje previo, esta opción es preferida dado que en ocasiones la lista se retrasa, e.g. al filtrar correos durante las epidemias, pero el mensaje le llegará al destinatario pronto.</li>
      </ul>
      <p>Claro que si haces esto, tal vez quieras eliminar algunos destinatarios extra 
      (por ejemplo, de post cruzados, u otras personas que ya hayan respondido).</p>
    </section>
  </chapter>
  <chapter filename="unsubscribe">
    <title>¿Cómo desuscribirse de las Listas?</title>
    <shorttitle>Desuscripción</shorttitle>
    <section name="unsubscribing">
      <title>¿Cómo me desuscribo?</title>
      <p>Para desuscribirse, <em>no</em> mande un mensaje a la lista.</p>
      <ol>
        <li>Vaya a la página de las<link url="/lists/index.php">Listas de Correo</link>.  <p>Nota:  no use el Internet Explorer del MacOS X.</p></li>
        <li>Seleccione el vínculo de la lista de la que desea desuscribirse.</li>
        <li>Vaya al pie de la página donde dice::  <quote>Para cambiar su suscripción (ajustar opciones como resumen y modos de entrega, obtener un recordatorio de tu password o desuscribirse), ingrese su dirección de correo suscrito:</quote>, e ingrese la dirección de correo electrónico donde esta recibiendo el correo de Fink, entonces dele click al botón de <quote>Edit Options</quote> .   </li>
        <li>En la página que se abre a continuación, hay un campo en la parte superior 
        izquierda donde se puede desuscribir.</li>
      </ol>
    </section>
  </chapter>
</document>

=== fink/website/xml/doc/doc.ja.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="index" lang="ja" >
<title>Fink - Documentation</title>
<shorttitle>Documentation</shorttitle>
<cvsid>$Id: doc.ja.xml,v 1.22 2019/01/19 10:11:12 nieder Exp $</cvsid>

<preface>
<p>
このページは、 Fink 用に書かれたドキュメントの一覧です。
ドキュメントの中には、 Fink を使わずに Mac OS X や Darwin だけを使う人、 Unix ソフトウェアのポートの仕方を知りたい人にも有用な情報もあります。
</p>
</preface>

<section name="userdoc"><title>ユーザー向けドキュメント</title>

<p>
現在のユーザー向け Fink ドキュメント:
</p>
<ul>
<li><varlink url="users-guide/index.php" varurl="users-guide/uguide.ja.html">Fink ユーザーガイド</varlink> -
Fink 本体のインストール、パッケージのインストール、新しい Fink リリースへのアップグレードなどが書かれています。
ソースとバイナリリリースの両方の説明が書かれています
</li>
<li><varlink url="advanced/index.php" varurl="advanced/advanced.en.html">Fink 上級者向けトピックガイド</varlink> -
ユーザーガイドよりも上級者向けのトピックをカバーしています</li>
<li><varlink url="x11/index.php" varurl="x11/x11.ja.html">Darwin と Mac OS X での X11</varlink> -
コンセプト、インストール、起動について書かれています (一般的な Darwin と Mac OS X ユーザー向け) </li>
</ul>

<p>
以下のドキュメントはより詳細ですが、内容が多少古くなっている上、今後メンテナンスされません。
（訳注 日本語版はありません）:
</p>
<ul>
<li><varlink url="install/index.php" varurl="install/install.en.html">Installation and Upgrading</varlink> - how
to install Fink or upgrade to a new version</li>
<li><varlink url="usage/index.php" varurl="usage/usage.en.html">Usage</varlink> - how to use Fink
and the installed software</li>
<li><varlink url="readme.php" varurl="readme.ja.html">Fink ReadMe</varlink> - the ReadMe for the
source distribution</li>
<li><varlink url="gitaccess/index.php" varurl="gitaccess/git.en.html">Git Access</varlink> - how to access the
Fink Git repository to get the latest source packages between
releases</li>
</ul>

</section>

<section name="developerdoc"><title>開発者向けドキュメント</title>

<ul>
<li><varlink url="security/index.php" varurl="security/sec-policy.ja.html">セキュリティーポリシー</varlink> - 
Fink のパッケージをメンテナンスしている人、したいと思っている人、必見</li>
<li><link url="/doc/UsingFink.pdf">Using Fink: A Developer's How To</link> (2MB pdf
file) - <link
url="http://conferences.oreillynet.com/macosx2002/"
>O'Reilly Mac OS X Conference</link> でのプレゼンテーション用スライド (
<link url="http://conferences.oreillynet.com/presentations/macosx02/morrison_david.ppt">PowerPoint ファイル</link> もあります) </li>
<li><varlink url="porting/index.php" varurl="porting/porting.en.html">Porting Tips</varlink> - 
Unix アプリケーションを Darwin へポートする際に有用な情報</li>
<li><varlink url="quick-start-pkg/index.php" varurl="quick-start-pkg/quick-start-pkg.en.html">パッケージ化チュートリアル</varlink> - 
パッケージ化マニュアルへにない、実例を用いた初心者向け紹介文書</li>
<li><varlink url="packaging/index.php" varurl="packaging/packaging.en.html">パッケージ化マニュアル</varlink> - 
Fink パッケージの作り方、メンテナンス方法</li>
<li><link url="http://wiki.finkproject.org/index.php/Fink">The Fink Developer Wiki</link> - 作成途中の開発に関連する資料など</li>
</ul>
</section>
<section name="otherdoc">
<title>Other Documents</title>
<ul>
<li><varlink url="multilingual/index.php" varurl="multilingual/multilingual.en.html">国際化ガイド</varlink> - 
現在進行中のウェブサイト国際化に関するドキュメント</li>
<li><varlink url="netiquette/index.php" varurl="netiquette/netiquette.en.html">メーリングリスト投稿時の注意</varlink> - 
メーリングリストを快適に保つために</li>
</ul>
</section>
</article>
