=== fink/website/xml/finkdoc.dtd
<!ENTITY % block "codeblock | ol | p | ul" >
<!ENTITY % inline "#PCDATA | code | strong | em | filename | link | varlink | tt | quote | xref" >

<!ENTITY fink_version "0.9.0" >
<!ENTITY fink_tool_version "0.45.4">


<!-- Root elements -->
<!ELEMENT article ( title, shorttitle, cvsid, preface?, section+ ) >
<!ATTLIST article filename ID #REQUIRED >
<!ATTLIST article lang CDATA "en" >
<!ATTLIST article fsroot CDATA "../" >

<!ELEMENT document ( title, shorttitle, cvsid, preface?, chapter+ ) >
<!ATTLIST document filename ID #REQUIRED >
<!ATTLIST document lang CDATA "en" >
<!ATTLIST document section CDATA "documentation" >
<!ATTLIST document fsroot CDATA "../../" >


<!-- Structure -->
<!ELEMENT chapter ( title, shorttitle, preface?, section+ ) >
<!ATTLIST chapter filename ID #REQUIRED >

<!ELEMENT title ( #PCDATA ) >
<!ELEMENT shorttitle ( #PCDATA ) >
<!ELEMENT cvsid ( #PCDATA ) >
<!ELEMENT preface ( p+ ) >

<!ELEMENT section (title?, ( %block; | itemtable )*) >
<!ATTLIST section name NMTOKEN #IMPLIED >
<!ATTLIST section translated (yes|no) "yes" >


<!-- Block elements -->
<!ELEMENT codeblock ( #PCDATA | em | strong )* >
<!ELEMENT p ( %inline; )* >
<!ATTLIST p translated (yes|no) "yes" >


<!-- Inline -->
<!ELEMENT code ( #PCDATA | em | strong )* >
<!ELEMENT em ( #PCDATA ) >
<!ELEMENT strong ( #PCDATA ) >
<!ELEMENT filename ( #PCDATA ) >
<!ELEMENT tt ( #PCDATA ) >
<!ELEMENT quote ( #PCDATA ) >


<!-- Links -->
<!ELEMENT link ( #PCDATA ) >
<!ATTLIST link url CDATA #REQUIRED >

<!-- VarLinks -->
<!ELEMENT varlink ( #PCDATA ) >
<!ATTLIST varlink url CDATA #REQUIRED >
<!ATTLIST varlink varurl CDATA #REQUIRED >


<!ELEMENT xref ( #PCDATA ) >
<!ATTLIST xref chapter IDREF #IMPLIED >
<!ATTLIST xref section NMTOKEN #IMPLIED >


<!-- Lists -->
<!ELEMENT ol ( li+ ) >
<!ELEMENT ul ( li+ ) >

<!ELEMENT li ( %inline; | codeblock | p | ol )* >

<!ELEMENT itemtable ( item+ ) >
<!ATTLIST itemtable labeld CDATA "Value" >
<!ATTLIST itemtable labelt CDATA "Field" >

<!ELEMENT item ( itemt, itemd ) >
<!ELEMENT itemt ( %inline; )* >
<!ELEMENT itemd ( %block; )* >

=== fink/website/xml/advanced/advanced.fr.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document SYSTEM "../finkdoc.dtd">
<document filename="index" lang="fr">
<title>Notions complexes dans Fink</title>
<shorttitle>Notions complexes</shorttitle>
<cvsid>$Id: advanced.fr.xml,v 1.7 2023/08/04 5:08:13 nieder Exp $</cvsid>
<preface>
<p>Ce document aborde quelques notions complexes qui ne se trouvent pas dans le <link url="/doc/users-guide/">Guide de l'utilisateur</link>.</p>
</preface>
<chapter filename="bindist">
<title>Mise en place d'un serveur de distribution binaire</title>
<shorttitle>Serveur de distribution binaire</shorttitle>
<section name="intro">
<title>Introduction</title>
<p>Cette section décrit une méthode d'utilisation d'un serveur central de compilation ( serveur "maître") pour distribuer des paquets binaires à tous les clients des stations de travail. Elle s'applique aux stations de travail utilisant plusieurs installations de Fink.</p>
<p><em>Note :</em> dans les instructions suivantes, on a supposé que toutes les machines clientes ont une version de fink supérieure ou égale à la version 0.24.0. Voir plus loin la section <xref section="remarks">remarques</xref> si les machines ont une version de fink antérieure.</p>
<p>La méthode se compose des étapes suivantes sur le <xref section="master">serveur "maître"</xref> et sur les <xref section="client">machines clientes</xref> :</p>
</section>
<section name="master">
<title>Étapes sur le serveur "maître" (serveur de compilation) </title>
<ol>
<li>Installez Fink dans le répertoire <filename>/opt/sw</filename> (chemin par défaut, utilisez un lien symbolique si nécessaire).</li>
<li>Construisez les paquets comme d'habitude. Il n'est pas nécessaire de les installer.</li>
<li><p>Exécutez <code>fink scanpackages</code> chaque fois que le jeu de paquets construits change. Fink générera alors des index apt pour tous les arbres activés.</p>
<p>Au lieu de la commande précédente, vous pouvez exécuter <code>fink cleanup</code>. Les paquets sources et binaires obsolètes seront alors supprimés. La commande <code>scanpackages</code> est appelée automatiquement à la fin du processus de nettoyage.</p></li>
<li>Démarrez un serveur web : vous pouvez, par exemple, activer "Partage Web personnel" dans la section Partage des Préférences Système, puis configurer <code>httpd</code> de telle sorte qu'il serve le répertoire <filename>/opt/sw/fink</filename> en ajoutant les lignes suivantes au fichier <filename>/etc/httpd/httpd.conf</filename> :
<codeblock>
Alias /fink /opt/sw/fink
&lt;Directory /opt/sw/fink&gt;
  Options Indexes FollowSymLinks
&lt;/Directory&gt;
</codeblock></li>
<li>Exécutez <code>sudo /usr/sbin/apachectl graceful</code> pour (re)démarrer votre serveur web.</li>
</ol>
<p>N'oubliez pas de réexécuter <code>fink scanpackages</code> (ou <code>fink cleanup</code>) chaque fois que vous construisez ou mettez à jour des paquets sur le serveur "maître", de façon à ce qu'ils soient disponibles sur les machines éloignées.</p>
<p><em>Notes</em> :</p>
<p>Vous pouvez aussi créer un utilisateur "fink" et ajouter les lignes ci-dessus au fichier <filename>/etc/httpd/users/fink.conf</filename>.</p>
<p>Si vous utilisez le paquet apache2 de Fink, vous devrez modifier les chemins ci-dessus.</p>
</section>
<section name="client">
<title>Étapes sur les machines clientes</title>
<ol>
<li>Installez Fink sur <filename>/opt/sw</filename> (chemin de base par défaut).</li>
<li>Exécutez <code>fink configure</code> et activez l'option de téléchargement des paquets à partir de la distribution binaire : "UseBinaryDist: true" dans le fichier <filename>/opt/sw/etc/fink.conf</filename>.</li>
<li>Ouvrez le fichier <filename>/opt/sw/etc/apt/sources.list</filename> et ajoutez-y les lignes correspondant à vos arbres Fink. Par exemple, si l'adresse IP de votre machine de compilation est 192.168.42.7, vous devez ajouter les lignes suivantes :
<codeblock>
deb http://192.168.42.7/fink stable main crypto
deb http://192.168.42.7/fink unstable main crypto
deb http://192.168.42.7/fink local main
</codeblock></li>
<li>Exécutez <code>fink selfupdate</code>. Vous devriez voir apparaître les lignes suivantes :
<codeblock>
...
Hit http://192.168.42.7 stable/main Packages
Hit http://192.168.42.7 stable/main Release
Hit http://192.168.42.7 stable/crypto Packages
...
</codeblock>
à la fin du processus de mise à jour, si le niveau de verbosité est supérieur ou égal à 1.</li>
</ol>
<p>L'exécution de <code>fink update-all</code> ou de <code>fink install &lt;paquet&gt;</code> téléchargera alors les paquets en tant que paquets binaires s'ils sont disponibles sur le serveur "maître".</p>
</section>
<section name="remarks">
<title>Remarques</title>
<ul>
<li>Le serveur "maître" doit utiliser une version de X11 identique à la plus ancienne version installée sur l'ensemble des clients. Par exemple, si l'une des machines clientes utilise X11 d'Apple, le serveur "maître" doit l'utiliser lui aussi.</li>
<li>Vous pouvez supprimer les paquets qui ne sont que des dépendances de compilation (c'est-à-dire qui ne sont pas nécessaires à l'exécution d'autres paquets). Le paquet <code>debfoster</code> permet de le faire facilement. Faîtes toutefois attention à ne pas supprimer de paquets essentiels, tel <code>apt</code>.</li>
<li>Si vous utilisez une version de fink inférieure à la version 0.24.0 sur une machine client, vous devez exécuter <code>sudo apt-get update</code> au lieu de <code>fink selfupdate</code>. Vous devez alors installer les paquets binaires via <code>sudo apt-get install &lt;paquet&gt;</code>. </li>
</ul>
<p>Ce document est adapté pour part de <link url="http://ranger.befunk.com/blog/archives/000258.html">"Sharing the Fink"</link> par RangerRick. Merci !</p>
</section>
</chapter>
</document>

=== fink/website/xml/doc/doc.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">
<article filename="index" lang="en">
  <title>Fink - Documentation</title>
  <shorttitle>Documentation</shorttitle>
  <cvsid>$Id: doc.en.xml,v 1.20 2019/01/19 10:11:12 nieder Exp $</cvsid>
  <preface>
    <p>
This is a collection of various documents written for Fink.
Some of the documents may also be useful to people who use Mac OS X
or Darwin without Fink and want to learn about porting Unix software.
</p>
  </preface>
  <section name="userdoc">
    <title>User Documentation</title>
    <p>
The current user documentation for Fink:
</p>
    <ul>
      <li><varlink url="users-guide/index.php" varurl="users-guide/uguide.en.html">Fink User's Guide</varlink> -
this covers installing Fink itself, installing packages, and upgrading
to a new Fink release. It contains instructions for both the source
and the binary release.
</li>
      <li><varlink url="advanced/index.php" varurl="advanced/advanced.en.html">Fink Advanced Topics Guide</varlink> -
covers more advanced concepts than those covered in the User's Guide.</li>
      <li><varlink url="x11/index.php" varurl="x11/x11.en.html">Running X11 on Darwin and Mac OS X</varlink> -
covers concepts, installation and launching (also intended for Darwin
and Mac OS X users in general)</li>
    </ul>
    <p>
A bunch of documents that are more complete, but slightly outdated and
no longer maintained:
</p>
    <ul>
      <li><varlink url="install/index.php" varurl="install/install.en.html">Installation and Upgrading</varlink> - how
to install Fink or upgrade to a new version</li>
      <li><varlink url="usage/index.php" varurl="usage/usage.en.html">Usage</varlink> - how to use Fink
and the installed software</li>
      <li><varlink url="readme.php" varurl="readme.en.html">Fink ReadMe</varlink> - the ReadMe for the
source distribution</li>
      <li><varlink url="gitaccess/index.php" varurl="gitaccess/git.en.html">Git Access</varlink> - how to access the
Fink Git repository to get the latest source packages between
releases</li>
    </ul>
  </section>
  <section name="developerdoc">
    <title>Developer Documentation</title>
    <ul>
      <li><varlink url="security/index.php" varurl="security/sec-policy.en.html">Security Policy Manual</varlink> - 
	  Mandatory read for all of those who either maintain packages in Fink or would like to add their own.</li>
      <li><link url="/doc/UsingFink.pdf">Using Fink: A Developer's How To</link> (2MB pdf
file) - slides from a presentation at the <link url="http://conferences.oreillynet.com/macosx2002/">O'Reilly Mac OS X Conference</link> (also available as a
<link url="http://conferences.oreillynet.com/presentations/macosx02/morrison_david.ppt">PowerPoint file</link>) </li>
      <li><varlink url="porting/index.php" varurl="porting/porting.en.html">Porting Tips</varlink> - notes for porting
Unix applications to Darwin</li>
      <li><varlink url="quick-start-pkg/index.php" varurl="quick-start-pkg/quick-start-pkg.en.html">Packaging Tutorial</varlink> - a complement to the Packaging Manual which focuses on real examples and introduces packaging to beginners.</li>
      <li><varlink url="packaging/index.php" varurl="packaging/packaging.en.html">Packaging Manual</varlink> - how to create and
maintain Fink packages</li>
      <li><link url="http://wiki.finkproject.org/index.php/Fink">The Fink Developer Wiki</link> - includes developer-related material that is under construction.</li>
    </ul>
  </section>
  <section name="otherdoc">
    <title>Other Documents</title>
    <ul>
      <li><varlink url="multilingual/index.php" varurl="multilingual/multilingual.en.html">Internationalization Guide</varlink> - material concerning
the ongoing website
internationalization 
effort</li>
      <li><varlink url="netiquette/index.php" varurl="netiquette/netiquette.en.html">Mailing List Netiquette</varlink> - how best to employ the Fink mailing lists.</li>
    </ul>
  </section>
</article>

=== fink/website/xml/doc/doc.zh.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="index" lang="zh" >
<title>Fink－文档</title>
<shorttitle>文档</shorttitle>
<cvsid>$Id: doc.zh.xml,v 1.18 2019/01/19 10:11:12 nieder Exp $</cvsid>

<preface>
<p>
这里收集了为 Fink 编写的各种文档。
有些文档可能会对使用 Mac OS X 的用户有用，或那些没有使用 Fink 但又向学习如何移植 Unix 软件的 Darwin 用户有用。
</p>
</preface>

<section name="userdoc"><title>用户文档</title>

<p>
当前 Fink 的用户文档：
</p>
<ul>
<li><varlink url="users-guide/index.php" varurl="users-guide/uguide.zh.html">Fink 用户指南</varlink> － 它涉及如何安装 Fink 自身，安装软件包，和升级到新的 Fink 版本。它包括对使用源代码版本和二进制版本的使用说明。
</li>
<li><varlink url="advanced/index.php" varurl="advanced/advanced.en.html">Fink Advanced Topics Guide</varlink> -
covers more advanced concepts than those covered in the User's Guide.</li>
<li><varlink url="x11/index.php" varurl="x11/x11.zh.html">在 Darwin 和 Mac OS X 上运行 X11</varlink> － 涉及有关概念，安装和启动（同时面向 Darwin 和 Mac OS X 用户）</li>
</ul>

<p>
很多更完整的文档，但稍微有点过期而且不再被维护：
</p>
<ul>
<li><varlink url="install/index.php" varurl="install/install.en.html">安装和升级</varlink> －　如何安装 Fink 或升级到新的版本</li>
<li><varlink url="usage/index.php" varurl="usage/usage.en.html">使用</varlink>  － 如何使用 Fink 及其安装的软件</li>
<li><varlink url="readme.php" varurl="readme.zh.html">Fink 自述</varlink> － 源代码发布版本的自述文件</li>
<li><varlink url="gitaccess/index.php" varurl="gitaccess/git.en.html">Git 访问</varlink> － 如何访问 Fink Git 库来在新版本发布前获取最新源代码包。</li>
</ul>

</section>

<section name="developerdoc"><title>开发者文档</title>

<ul>
<li><varlink url="security/index.php" varurl="security/sec-policy.en.html"> 网络安全策略手册</varlink> - 所有在 Fink 中有管理软件包或打算向里面添加软件包的人都必须阅读。</li>
<li><link url="/doc/UsingFink.pdf">使用 Fink：开发者使用指南</link>  (2MB pdf 文件，英文版) － 一组用于 <link url="http://conferences.oreillynet.com/macosx2002/">O'Reilly Mac OS X 大会</link>上演示的幻灯片（同时也有 <link url="http://conferences.oreillynet.com/presentations/macosx02/morrison_david.ppt">PowerPoint 文件</link>版本）</li>
<li><varlink url="porting/index.php" varurl="porting/porting.zh.html">移植技巧提示</varlink> － 关于如何移植 Unix 软件到 Darwin 上的资料</li>
<li><varlink url="quick-start-pkg/index.php" varurl="quick-start-pkg/quick-start-pkg.en.html">Packaging Tutorial</varlink> - a complement to the Packaging Manual which focuses on real examples and introduces packaging to beginners.</li>
<li><varlink url="packaging/index.php" varurl="packaging/packaging.zh.html">软件打包手册</varlink> － 如何创建和维护 Fink 软件包</li>
<li><link url="http://wiki.finkproject.org/index.php/Fink">The Fink Developer Wiki</link> - includes developer-related material that is under construction.</li>
</ul>

</section>

<section name="otherdoc">
    <title>其它文档</title>
    <ul>
      <li><varlink url="multilingual/index.php" varurl="multilingual/multilingual.zh.html">国际化指南</varlink> ─ 有关目前网站所在进行的国际化工作的文档</li>
      <li><varlink url="netiquette/index.php" varurl="netiquette/netiquette.zh.html">邮件列表使用规则</varlink>-如何更好地使用 Fink 邮件列表。</li>
    </ul>
  </section>
</article>

=== fink/website/xml/netiquette/netiquette.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../finkdoc.dtd">
<document filename="index" lang="en">
  <title>How to Post to a Fink Mailing List</title>
  <shorttitle>netiquette</shorttitle>
  <cvsid>$Id: netiquette.en.xml,v 1.6 2023/08/04 5:23:15 nieder Exp $</cvsid>
  <preface>
    <p><em>This document is under construction.</em></p>
    <p>This document is intended to be a guideline for new posters to a Fink mailing list.  The idea is to educate users of the lists on how to post effectively, in order to promote efficient solutions to problems.  </p>
    <p>You may have been referred to a page on this list in a reply to a post.  Don't take offense!  What has most likely happened is that you need to provide more information to clarify the cause of your problem, and what you need to provide is listed here.</p>
  </preface>
  <chapter filename="before-post">
    <title>What to do Before You Post</title>
    <shorttitle>Before posting</shorttitle>
    <section name="research">
      <title>Research your question.</title>
      <p>You should do a little research before you post, in case your question has been answered before.  Examples of places to check are:</p>
      <ul>
        <li>the online documentation</li>
        <li>the mailing list archives</li>
        <li>Google</li>
      </ul>
    </section>
  </chapter>
  <chapter filename="first-post">
    <title>Initial Post</title>
    <shorttitle>Initial</shorttitle>
    <section name="system">
      <title>What do you have installed?</title>
      <p>If you are having a problem installing a package, you should provide the following information about your system:</p>
      <ul>
        <li>Your OS version.</li>
        <li>The version of Fink you are running.  A useful technique here is to post the output that you get from running<codeblock>fink --version</codeblock>in a terminal window.</li>
        <li>You should specify whether you are installing from binaries, e.g. using <code>apt-get</code>, or from source, e.g. using <code>fink install</code>.<p>If the latter, you should also indicate what version of the Developer Tools you are using.</p></li>
        <li><p>If you are installing a package that requires X11, you should specify what you are using:  Apple's X11 or XFree86.  If the latter, specify its version.  </p><p>If in doubt, go ahead and provide this information.</p></li>
      </ul>
    </section>
    <section name="problem-description">
      <title>What's Going Wrong?</title>
      <ul>
        <li><em>Specify the name and version of the package that is causing the problem.</em>  <p>This should be in the subject line of your message.</p><p>This means that if you are having problems with <code>foo-3.141-6</code>, don't just report a problem with <code>foo</code>.</p><p>In particular, if you are installing a package (e.g. <code>baz-2.18-1</code>) that depends on other packages, (<code>foo-3.141-6</code>, <code>bar-16.0-9</code>, ...) , and you are having problems with <code>foo</code>, you should report a problem with <code>foo-3.141-6</code>, not with <code>baz-2.18-1</code>.</p></li>
        <li><em>Describe the problem.</em>  <p>This means that you should post a sample of an error message.</p><ol>
            <li>For binary installation problems, start with where the troublesome package is being unpacked:<codeblock>...
Selecting previously deselected package foo
error unpacking foo
...</codeblock>and go on until the end.<p></p></li>
            <li>There are a few possible issues with installation from source:<ol>
                <li>If the failure is during the initial configuration, this is usually immediate.  Post from the last couple of tests that were run before the error message on to the end:<codeblock>....
Checking for bar-config...no
Error:  bar-config not found
....</codeblock><p>If you think it might help, then you can post the relevant section of the configuration log file, e.g. <filename>/opt/sw/src/foo-3.141-6/foo-3.141/config.log</filename>.  <em>Please don't post the whole file, since it can be large.</em></p></li>
                <li>Or, the error can show up immediately when you've actually started building the package.  In this case, post from the last line the compiler tried to run to the end:<codeblock>...
gcc &lt;flags, files etc.&gt;
&lt;error messages&gt;
...</codeblock></li>
                <li>If you get the dreaded <code>execution of mv failed</code> error, you'll be told to search your build output for an earlier error, so you may want to try hunting for it before you post.</li>
              </ol></li>
          </ol>    </li>
      </ul>
    </section>
    <section name="remedies">
      <title>What have you tried?</title>
      <p>It's a good idea to mention what you've tried, e.g.</p>
      <ul>
        <li>Instructions in the FAQ or other documentation</li>
        <li>Removing packages that appeared to cause a conflict</li>
        <li>Rebuilding/reinstalling</li>
        <li>Updating package descriptions again</li>
        <li>etc.</li>
      </ul>
      <p>That way, people won't start by suggesting things that you've already done.</p>
    </section>
    <section name="future-plans">
      <title>What will you try next?</title>
      <p>A couple of items come under this category:</p>
      <ul>
        <li>Posting what you plan to do if you don't get an immediate response.</li>
        <li>Asking about the suitability of a course of action.</li>
      </ul>
    </section>
  </chapter>
  <chapter filename="reply">
    <title>Replying to Posts</title>
    <shorttitle>Replying</shorttitle>
    <preface>
      <p>This chapter covers what to do when replying to posts.</p>
    </preface>
    <section name="reply-to-list">
      <title>Make Sure to Reply to the List</title>
      <p>Unlike some other mailing lists to which you may be subscribed, the Fink lists are set up such that if you simply reply to a message, you will reply to the person who posted it, but <em>not</em> to the list.  Please make sure that you reply to the list:  </p>
      <ul>
        <li>You get more people looking at your problem.</li>
        <li>You don't monopolize one person's time.  Remember:  people who reply on the lists are volunteers.</li>
        <li>Others can benefit, as well.  Having the full set of email exchanges in the public view means that they go into the mailing list archives, and may ultimately wind up in the documentation.</li>
      </ul>
      <p>Frequently people will use <quote>Reply to All</quote> to accomplish this:</p>
      <ul>
        <li>It's typically just as easy as hitting "Reply".</li>
        <li>Even though this sends both to the list and to the author of the prior message, this can be desirable, since sometimes the list mail gets delayed, e.g. for virus filtering during major outbreaks, and the message will get to the prior poster more quickly.</li>
      </ul>
      <p>However, if you do this, you may want to trim out any extra recipients (from crossposts, or other people who have replied on this thread).</p>
    </section>
  </chapter>
  <chapter filename="unsubscribe">
    <title>How to Unsubscribe from the Lists</title>
    <shorttitle>Unsubscribing</shorttitle>
    <section name="unsubscribing">
      <title>How do I unsubscribe?</title>
      <p>To unsubscribe, <em>don't</em> send a message to the list.</p>
      <ol>
        <li>Go to the <link url="/lists/index.php">Mailing Lists</link> page.  <p>Note:  don't use the MacOSX version  Internet Explorer.</p></li>
        <li>Select the link for the list from which you wish to unsubscribe.</li>
        <li>Go to the bottom of the page where it says:  <quote>To change your subscription (set options like digest and delivery modes, get a reminder of your password, or unsubscribe), enter your subscription email address:</quote>, and enter the email address where you are receiving the Fink mail, then click the <quote>Edit Options</quote> button.   </li>
        <li>On the page that opens up next, there's a field in the upper left where you can unsubscribe.</li>
      </ol>
    </section>
  </chapter>
</document>
