=== fink/website/xml/finkfaq.dtd
<!ENTITY % block "codeblock | p | ul" >
<!ENTITY % inline "#PCDATA | code | em | filename | link | tt | quote | xref" >

<!ENTITY fink_version "0.9.0" >
<!ENTITY fink_tool_version "0.44.1" >


<!-- Root elements -->

<!ELEMENT document ( title, shorttitle, cvsid, preface?, chapter+ ) >
<!ATTLIST document filename ID #REQUIRED >
<!ATTLIST document lang CDATA "en" >
<!ATTLIST document section CDATA "faq" >
<!ATTLIST document fsroot CDATA "../" >


<!-- Structure -->
<!ELEMENT chapter ( title, shorttitle, faqentry+ ) >
<!ATTLIST chapter filename ID #REQUIRED >

<!ELEMENT title ( #PCDATA ) >
<!ELEMENT shorttitle ( #PCDATA ) >
<!ELEMENT cvsid ( #PCDATA ) >
<!ELEMENT preface ( p+ ) >

<!ELEMENT faqentry ( question, answer ) >
<!ATTLIST faqentry name ID #REQUIRED >

<!ELEMENT question ( p ) >
<!ATTLIST question translated (yes|no) "yes" >
<!ELEMENT answer ( %block; )* >
<!ATTLIST answer translated (yes|no) "yes" >


<!-- Block elements -->
<!ELEMENT codeblock ( #PCDATA | em )* >
<!ELEMENT p ( %inline; )* >
<!ATTLIST p translated (yes|no) "yes" >


<!-- Inline -->
<!ELEMENT code ( #PCDATA | em )* >
<!ELEMENT em ( #PCDATA ) >
<!ELEMENT filename ( #PCDATA ) >
<!ELEMENT tt ( #PCDATA ) >
<!ELEMENT quote ( #PCDATA ) >


<!-- Links -->
<!ELEMENT link ( #PCDATA ) >
<!ATTLIST link url CDATA #REQUIRED >

<!ELEMENT xref ( #PCDATA ) >
<!ATTLIST xref chapter IDREF #IMPLIED >
<!ATTLIST xref section NMTOKEN #IMPLIED >


<!-- Lists -->
<!ELEMENT ul ( li+ ) >
<!ELEMENT li ( %inline; | codeblock | p )* >

=== fink/website/xml/faq/faq.zh.xml
<?xml version = '1.0' encoding = 'utf-8'?>
<!DOCTYPE document SYSTEM "../finkfaq.dtd">
<document lang="zh" filename="index" >
  <title>Fink 常见疑问（F.A.Q.）</title>
  <shorttitle>常见疑问（F.A.Q.）</shorttitle>
  <cvsid>$Id: faq.zh.xml,v 1.36 2020/05/31 13:43:40 nieder Exp $</cvsid>
  <preface>
    <p>这是一个关于 Fink 经常被问到的问题的清单。和多数的 FAQs 一样，其中一些问题来自于实际的问题，而另外一些则是假设存在的。它更接近于一份专门以问答形式编写的文档。</p>
    <p>本 FAQ 由几页组成，每部分一页。所有的问题都会在下面的目录中列出并链接到合适的位置。</p>
  </preface>
  <chapter filename="general" >
    <title>一般性问题</title>
    <shorttitle>一般性问题</shorttitle>
    <faqentry name="what" >
      <question>
        <p>什么是 Fink？</p>
      </question>
      <answer>
        <p>
Fink 希望把越来越多的 Unix 软件带到 Mac OS X，因此它的两个主要目标是：
</p>
        <p>
第一目标是移植软件到 Mac OS X 上。
我们寻找现成的开放源代码的 Unix 软件，并对它做必要的修正以使得它可以在 Mac OS X 上编译和运行。有些时候这很容易，但对一些软件包，也可能很难甚至不可能。
我们试图通过提供一些工具和文档来使它更容易些。
</p>
        <p>
第二目标是使我们的成果能够被普通用户所使用。
为了实现这个目标，我们建立了一个的软件包管理工具。它移植自 Linux 上两个主要的程序 <code>dpkg</code> 和　<code>apt-get</code>，它们原来是为<link url="http://www.debian.org/" >Debian GNU/Linux</link> 项目编写的。
我们的软件包的二进制发行版使用 <code>.deb</code> 软件包格式。
对于从源代码构建软件包，我们使用我们自己的工具，称为 <code>fink</code>，它可以生成 <code>.deb</code> 软件包文件。
</p>
      </answer>
    </faqentry>
    <faqentry name="naming" >
      <question>
        <p>Fink 是什么意思？</p>
      </question>
      <answer>
        <p>没有什么特别含义，只是一个名字而已。它也不是什么缩写。</p>
        <p>事实上，Fink 在德语中是雀类（属于鸟类）的意思。当我在给这个项目起名的时候，操作系统的名称 Darwin，使我联想到查尔斯·达尔文，Galapagos 群岛和进化论。然后我想起了学校时学过的关于达尔文雀的东西，以及它们尖尖的嘴...</p>
      </answer>
    </faqentry>
    <faqentry name="bsd-ports" >
      <question>
        <p>Fink 和 BSD port 机制有什么区别（它被包括在 OpenPackages 和 GNU-Darwin 中）？</p>
      </question>
      <answer>
        <p>一些主要优点：</p>
        <ul>
          <li>
            <p>
它用 Perl 编写，而不是 make/shell。
这样它并不依赖于 BSD make 的某个特定功能。
这样不需要表明软件包必须使用 GNU make 来构建。
</p>
          </li>
          <li>
            <p>
dpkg 提供完善的二进制包管理机制－平滑升级，对配置文件的特别处理，虚拟软件包，以及其它高级依赖关系设置。
</p>
          </li>
          <li>
            <p>
除非特别指明，Fink 不会安装到 /usr/local。也不需要对 /usr/bin/make 或其它系统本身的命令进行修正。
这使得它的使用会更安全，并最大限度降低与 Mac OS X 和第三方软件包可能造成的冲突。
</p>
          </li>
        </ul>
      </answer>
    </faqentry>
    <faqentry name="usr-local" >
      <question>
        <p>为什么 Fink 不安装在 /usr/local？</p>
      </question>
      <answer>
        <p>有几个原因，总括来说是 &quot;可能会被损坏&quot;。</p>
        <p>原因一：第三方软件。/usr/local 是存放不是由系统提供的第三方软件的地方。这意味着这是一个放杂七杂八东西的好地方。同时，这也意味着其它人也会放杂七杂八的东西到那里。多数的安装流程只是简单地覆盖那里的东西——对 dpkg 也是这样。当然，用户可以选择不安装第三方软件到 /usr/local。不幸的是，多数的安装程序并不事先告诉你它会安装到哪里。</p>
        <p>原因二：/usr/local/bin 在默认的 PATH 设置中。这意味着你的 shell 程序不需要什么其它设置就可以找到你安装的程序。但这意味着如果你不想使用这个程序，你需要进行额外的设置。极端情况下，它会影响系统本身——由需要部分依赖于 shell 脚本。</p>
        <p>原因三：编译工具默认搜索 /usr/local 目录。编译器会在 /usr/local/include 寻找头文件，连接器会在 /usr/local/lib 寻找连接库。同样，有些时候这会显得方便些，但在有需要的时候会很难禁用这个特性。通过把一个错误的 <code>stdio.h</code> 文件放到 /usr/local/include 目录中，你就很容易使得编译器出错。</p>
        <p>总的来说，把 Fink 安装到 /usr/local 是可能的。安装程序会明确警告你，但如果你确认你同意这样做的风险，它会按你的要求去做。</p>
      </answer>
    </faqentry>
    <faqentry name="why-sw" >
      <question>
        <p>为什么选择 /sw？</p>
      </question>
      <answer>
        <p>这个选择基本上是很随意的，但是基于实践（升级）的理由以及它在避免于其它软件包系统冲突方面是足够安全的，在可以遇见的将来仍然会保持这样。</p>
      </answer>
    </faqentry>
  </chapter>
  <chapter filename="relations" >
    <title>与其它项目的关系</title>
    <shorttitle>关系</shorttitle>
    <faqentry name="upstream" >
      <question>
        <p>你是否会把你的补丁反馈给上游维护者？</p>
      </question>
      <answer>
        <p>
我们正在尝试这么做。
有些时候反馈补丁是很容易的，在下一个版本出来以后会皆大欢喜。
不幸的是对于多数软件包并不那么容易。
一些常见的原因：
</p>
        <ul>
          <li>Fink 软件包的维护者很忙，没有时间将补丁发回给上游的维护者并附上需要修改的解释。</li>
          <li>上游维护者拒绝接受补丁。这样做有很多正常的理由。多数的上游维护者都强烈希望保持代码，配置检测的整洁，以及与其它平台的兼容。</li>
          <li>上游维护者接受了补丁，但需要数周或数月才会发布新的版本。</li>
          <li>软件包已经被原始作者所放弃，因此不会有新的融合了补丁的版本发布。</li>
        </ul>
      </answer>
    </faqentry>
    <faqentry name="debian" >
      <question>
        <p>你们和 Debian 项目的关系是什么？你们在把 Debian Linux 移植到 Mac OS X 上吗？</p>
      </question>
      <answer>
        <p>
Fink 和
<link url="http://www.debian.org" >Debian</link> 之间没有正式的关系。
Fink <em>不是</em> Debian GNU/Linux 发布版的一个移植。
我们的确移植了 Debian 的软件包管理工具（dpkg，dselect，apt-get），并使用这些工具以及 .deb 二进制包的格式。
实际的软件包是针对 Mac OS X / Darwin 进行了修正，并不使用 Debian 原始的包格式。
</p>
      </answer>
    </faqentry>
    <faqentry name="apple" >
      <question>
        <p>你们和苹果公司的关系是什么？</p>
      </question>
      <answer>
        <p>
          <link url="http://www.apple.com/" >苹果公司</link>了解 Fink 的存在并作为他们开放源码支持的一部分给予过我们一些帮助。
在 2001 年夏秋两季，他们给我们提供了新的 Mac OS X 的预发布版本以希望 Fink 软件包可以在它发布的时候能与它相配合。
引文：
<em>&quot;希望这会明确消除对于我们不愿意提供（帮助）的怀疑。我们将在开放源代码的游戏中逐步做得更好。&quot;</em>
感谢你，苹果公司！
</p>
      </answer>
    </faqentry>
    <faqentry name="darwinports" >
      <question>
        <p>你们和 Darwinports 的关系是什么？</p>
      </question>
      <answer translated="no">
        <!-- start translation -->
        <p>Darwinports and Fink are complementary projects. There is some overlap between the two projects, and several people contribute to both the Fink and DarwinPorts projects. For example, Benjamin Reed is doing the KDE packages for both. Darwinports and Fink are free to make use of each other's patches, and we have discussed collaboration on a new dependency engine.</p>
        <!-- end translation -->
        <p>
			OpenDarwin 尝试用一种不同的方法来重头建立软件包系统。请阅读 <link url="http://darwinports.opendarwin.org/" >OpenDarwin.org</link> 上的声明来获取详细信息。
		</p>
      </answer>
    </faqentry>
  </chapter>
  <chapter filename="mirrors" >
    <title>Fink 镜像</title>
    <shorttitle>镜像服务器</shorttitle>
    <faqentry name="when-use" >
      <question>
        <p>什么是 Fink 镜像？</p>
      </question>
      <answer>
        <p>
	Fink 镜像是一些 rsync 服务器，它镜像保存 Fink 的当前和稳定版本的描述文件。Fink 需要使用这些描述文件来从源代码构建软件包。
       </p>
      </answer>
    </faqentry>
    <faqentry name="why" >
      <question>
        <p>为什么我需要使用 rsync 镜像服务器？</p>
      </question>
      <answer>
        <p>Rsync 是一种很快速的协议。它可以用比过去的 CVS 更新方法更快的速度来更新描述文件。另外，CVS 总是通过 sourceforge.net 进行更新，而 rsync 则可以选择离你比较近的镜像服务器进行更新。</p>
      </answer>
    </faqentry>
    <faqentry name="where" >
      <question>
        <p>在哪里我可以找到关于 Fink 镜像的更多信息？</p>
      </question>
      <answer>
        <p>所有的 Fink 镜像都建立在 finkmirrors.net 域名之下。http://finkmirrors.net/ 这个网站会提供更多的信息。
</p>
      </answer>
    </faqentry>
    <faqentry name="when-not" >
      <question>
        <p>我不能连接 rsync 服务器，我应该怎么办？</p>
      </question>
      <answer>
        <p>有些时候，一些很严格的防火墙规则会进制你访问 rsync 服务。如果是这样的话，简单的办法是使用 CVS 方式。
</p>
      </answer>
    </faqentry>
    <faqentry name="otherinfogone" >
      <question>
        <p>我现在已经改换到 rsync 方法，但所有没有用到的代码树都消失了？</p>
      </question>
      <answer>
        <p>这时正常现象。rsync 只会更新活跃的代码树，比方说，10.3。同时它也会删除 CVS
子目录。
</p>
      </answer>
    </faqentry>
    <faqentry name="howswitch" >
      <question>
        <p>我怎么在这两种方法中切换？</p>
      </question>
      <answer>
        <p>使用 fink selfupdate-rsync 或 fink selfupdate-cvs 来切换到 rsync 或 CVS。</p>
      </answer>
    </faqentry>
    <faqentry name="Master" >
      <question>
        <p>什么是 Distfiles 镜像？</p>
      </question>
      <answer>
        <p>有些时候从互联网上获取某个版本的源代码会比较困难。Distfile 镜像会保存这些 Fink 需要使用的源代码软件包。</p>
      </answer>
    </faqentry>
  </chapter>
  <chapter filename="upgrade-fink" >
    <title>升级 Fink （解决特定版本的问题）</title>
    <shorttitle>升级 Fink</shorttitle>
    <faqentry name="leopard-bindist1">
      <question translated="no">
        <p>Fink doesn't see new packages even after I've run an rsync or cvs selfupdate.</p>
      </question>
      <answer translated="no">
        <p>This is a current issue for people on OS 10.5 using the binary installer. Check your version:</p>
        <codeblock>fink --version</codeblock>
        <p>If you currently have <code>fink-0.27.13-41</code>, which is the version that comes
	with the installer, or <code>fink-0.27.16-41</code>, then there are a couple of options.</p>
	<ul>
	  <li>
	    <em>rsync (preferred):</em>  Run the sequence below
	    <codeblock>fink selfupdate
fink selfupdate-rsync
fink index -f
fink selfupdate</codeblock>
	  </li>
	  <li>
	    <em>cvs (alternate):</em>  Run
	    <codeblock>fink selfupdate-cvs
fink index -f
fink selfupdate</codeblock>
	  </li>
	</ul>
        <p>Either will bring you the newest <code>fink</code> version.</p>
      </answer>
    </faqentry>

    <faqentry name="leopard-bindist2">
      <question translated="no">
        <p>When I try to install stuff I get 'Can't resolve dependency "fink (>= 0.28.0)"'</p>
      </question>
      <answer translated="no">
        <p>Apply the fix from <xref section="leopard-bindist1">the prior entry.</xref></p>
      </answer>
    </faqentry>
    <faqentry name="stuck-gettext">
      <question translated="no"><p>Fink tells me to run 'sudo apt-get install libgettext3-dev=0.14.5-2' to clear up inconsistent dependencies but I'm still stuck.</p></question>
      <answer translated="no">
	<p>There is a timestamp issue with the <em>libgettext3</em> package description:  0.14.5-2 is an outdated version.  Run</p>
	<codeblock>fink index -f
fink update libgettext3-dev	
	</codeblock>
	<p>to update the package description cache and then the package.</p>
      </answer>
    </faqentry>
    <faqentry name="stuck-dpkg">
      <question translated="no"><p>Fink tells me 'Can't resolve dependency "dpkg (>= 1.10.21-1229)" for package "dpkg-base-files-0.3-1"'.  How do I solve this?</p></question>
      <answer translated="no">
	<p>There is a timestamp issue with the updated <em>dpkg</em> package description.  Run</p>
	<codeblock>fink index -f
fink selfupdate
	</codeblock>
	<p>to update the package description cache and then to install <code>dpkg</code> and <code>dpkg-base-files</code>.</p>
      </answer>
    </faqentry>
  </chapter>
  <chapter filename="usage-fink" >
    <title>安装，使用和维护 Fink</title>
    <shorttitle>Fink 的使用</shorttitle>
    <faqentry name="what-packages" >
      <question>
        <p>我怎么知道 Fink 支持那些软件包？</p>
      </question>
      <answer>
        <p>
